// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeDialPeerVoice(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "type", "voip"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "description", "Outbound to CUCM"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "preference", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "huntstop", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "shutdown", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "vad", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "session_protocol", "sipv2"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeDialPeerVoiceConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeDialPeerVoiceConfig() string {
	config := `resource "iosxe_dial_peer_voice" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	tag = 100` + "\n"
	config += `	type = "voip"` + "\n"
	config += `	description = "Outbound to CUCM"` + "\n"
	config += `	preference = 1` + "\n"
	config += `	huntstop = false` + "\n"
	config += `	shutdown = false` + "\n"
	config += `	vad = true` + "\n"
	config += `	session_protocol = "sipv2"` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_dial_peer_voice" "test" {
			tag = 100
			depends_on = [iosxe_dial_peer_voice.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
