// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeSIPUA(t *testing.T) {
	if os.Getenv("C8000V") == "" {
		t.Skip("skipping test, set environment variable C8000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "transport_udp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "transport_tcp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "transport_tcp_tls", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "sip_server", "ipv4:10.0.0.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "redirection", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "handle_replaces", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "reason_header_override", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "host_registrar", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "max_forwards", "70"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "disable_early_media", "180"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "retry_invite", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "retry_register", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "retry_rel1xx", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "retry_response", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "retry_keepalive", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_expires", "180000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_trying", "500"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_connection_aging_tls", "720"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_options", "500"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_keepalive_active", "120"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "timers_keepalive_down", "30"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "connection_reuse", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_sip_ua.test", "connection_reuse_via_port", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeSIPUAConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeSIPUAConfig() string {
	config := `resource "iosxe_sip_ua" "test" {` + "\n"
	config += `	transport_udp = true` + "\n"
	config += `	transport_tcp = true` + "\n"
	config += `	transport_tcp_tls = true` + "\n"
	config += `	sip_server = "ipv4:10.0.0.1"` + "\n"
	config += `	redirection = true` + "\n"
	config += `	handle_replaces = true` + "\n"
	config += `	reason_header_override = true` + "\n"
	config += `	host_registrar = true` + "\n"
	config += `	max_forwards = 70` + "\n"
	config += `	disable_early_media = "180"` + "\n"
	config += `	retry_invite = 6` + "\n"
	config += `	retry_register = 6` + "\n"
	config += `	retry_rel1xx = 6` + "\n"
	config += `	retry_response = 6` + "\n"
	config += `	retry_keepalive = 6` + "\n"
	config += `	timers_expires = 180000` + "\n"
	config += `	timers_trying = 500` + "\n"
	config += `	timers_connection_aging_tls = 720` + "\n"
	config += `	timers_options = 500` + "\n"
	config += `	timers_keepalive_active = 120` + "\n"
	config += `	timers_keepalive_down = 30` + "\n"
	config += `	connection_reuse = true` + "\n"
	config += `	connection_reuse_via_port = true` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_sip_ua" "test" {
			depends_on = [iosxe_sip_ua.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
