// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &VoiceServiceVoIPDataSource{}
	_ datasource.DataSourceWithConfigure = &VoiceServiceVoIPDataSource{}
)

func NewVoiceServiceVoIPDataSource() datasource.DataSource {
	return &VoiceServiceVoIPDataSource{}
}

type VoiceServiceVoIPDataSource struct {
	data *IosxeProviderData
}

func (d *VoiceServiceVoIPDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voice_service_voip"
}

func (d *VoiceServiceVoIPDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Voice Service VoIP configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"address_hiding": schema.BoolAttribute{
				MarkdownDescription: "Address hiding (SIP-SIP)",
				Computed:            true,
			},
			"media_bulk_stats": schema.BoolAttribute{
				MarkdownDescription: "Retrieve bulk statistics is enabled",
				Computed:            true,
			},
			"media_statistics": schema.BoolAttribute{
				MarkdownDescription: "Media statistics is enabled",
				Computed:            true,
			},
			"media_disable_detailed_stats": schema.BoolAttribute{
				MarkdownDescription: "Disable detailed stats collection about the calls present",
				Computed:            true,
			},
			"mode_border_element": schema.BoolAttribute{
				MarkdownDescription: "Mode setting for Border-Element",
				Computed:            true,
			},
			"allow_connections_sip_to_sip": schema.BoolAttribute{
				MarkdownDescription: "to-type sip",
				Computed:            true,
			},
			"redirect_ip2ip": schema.BoolAttribute{
				MarkdownDescription: "Redirect IP-to-IP calls",
				Computed:            true,
			},
			"rtcp_keepalive": schema.BoolAttribute{
				MarkdownDescription: "Generate RTCP keepalive report",
				Computed:            true,
			},
			"redundancy_group": schema.Int64Attribute{
				MarkdownDescription: "Associate redundancy-group with voice HA",
				Computed:            true,
			},
			"dtmf_interworking": schema.StringAttribute{
				MarkdownDescription: "Dtmf Interworking",
				Computed:            true,
			},
			"emergency": schema.StringAttribute{
				MarkdownDescription: "List of Emergency Numbers",
				Computed:            true,
			},
			"gcid": schema.BoolAttribute{
				MarkdownDescription: "Enable Global Call Identification for voip",
				Computed:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: "Stop VoIP services gracefully without dropping active calls",
				Computed:            true,
			},
			"rtcp_all_pass_through": schema.BoolAttribute{
				MarkdownDescription: "Pass through all the rtcp in datapath",
				Computed:            true,
			},
			"ip_address_trusted_authenticate": schema.BoolAttribute{
				MarkdownDescription: "ip address trusted (toll fraud prevention) authenticate control flag",
				Computed:            true,
			},
			"ip_address_trusted_call_block": schema.BoolAttribute{
				MarkdownDescription: "ip address trusted (toll fraud prevention) call-block",
				Computed:            true,
			},
			"ip_address_trusted_list_ipv4": schema.ListNestedAttribute{
				MarkdownDescription: "ip address trusted (toll fraud prevention) list entry",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"address": schema.StringAttribute{
							MarkdownDescription: "IPv4 Address",
							Computed:            true,
						},
						"mask": schema.StringAttribute{
							MarkdownDescription: "IPv4 Address Mask",
							Computed:            true,
						},
					},
				},
			},
			"srtp_fallback": schema.BoolAttribute{
				MarkdownDescription: "Allow Secure calls fallback to non secure",
				Computed:            true,
			},
			"supplementary_service_sip_moved_temporarily": schema.BoolAttribute{
				MarkdownDescription: "enable/disable sip moved-temporarily",
				Computed:            true,
			},
			"supplementary_service_sip_handle_replaces": schema.BoolAttribute{
				MarkdownDescription: "Handle INVITE with REPLACES header (SIP-SIP only)",
				Computed:            true,
			},
			"supplementary_service_sip_refer": schema.BoolAttribute{
				MarkdownDescription: "enable/disable sip refer",
				Computed:            true,
			},
			"supplementary_service_media_renegotiate": schema.BoolAttribute{
				MarkdownDescription: "Enable/disable Media Renegotiation",
				Computed:            true,
			},
			"fax_protocol": schema.StringAttribute{
				MarkdownDescription: "The system-wide fax protocol type",
				Computed:            true,
			},
			"fax_fallback": schema.StringAttribute{
				MarkdownDescription: "fax transport to use if T.38 unsupported on far end",
				Computed:            true,
			},
			"trace": schema.BoolAttribute{
				MarkdownDescription: "Voip Trace configuration",
				Computed:            true,
			},
			"trace_shutdown": schema.BoolAttribute{
				MarkdownDescription: "Shut Voip Trace debugging",
				Computed:            true,
			},
			"stun_flowdata_agent_id": schema.Int64Attribute{
				MarkdownDescription: "Set Authorization Agent Id",
				Computed:            true,
			},
			"stun_flowdata_boot_count": schema.Int64Attribute{
				MarkdownDescription: "Set boot count",
				Computed:            true,
			},
			"sip_call_service_stop": schema.BoolAttribute{
				MarkdownDescription: "Stop SIP service - Active calls not affected",
				Computed:            true,
			},
			"sip_registrar_server_expires_max": schema.Int64Attribute{
				MarkdownDescription: "Default registration max expires time",
				Computed:            true,
			},
			"sip_registrar_server_expires_min": schema.Int64Attribute{
				MarkdownDescription: "Default registration min expires time",
				Computed:            true,
			},
			"sip_session_refresh": schema.BoolAttribute{
				MarkdownDescription: "Enable SIP session timer",
				Computed:            true,
			},
			"sip_session_transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - TLS over TCP",
				Computed:            true,
			},
			"sip_header_passing": schema.BoolAttribute{
				MarkdownDescription: "SIP Headers need to be passed to Applications",
				Computed:            true,
			},
			"sip_error_passthru": schema.BoolAttribute{
				MarkdownDescription: "SIP error response pass-thru functionality",
				Computed:            true,
			},
			"sip_referto_passing": schema.BoolAttribute{
				MarkdownDescription: "Refer-To needs to be passed through for transfer",
				Computed:            true,
			},
			"sip_asserted_id_pai": schema.BoolAttribute{
				MarkdownDescription: "Use privacy asserted identity",
				Computed:            true,
			},
			"sip_asymmetric_payload_full": schema.BoolAttribute{
				MarkdownDescription: "Asymmetric Support for dynamic codec and dtmf payloads",
				Computed:            true,
			},
			"sip_srtp_negotiate_cisco": schema.BoolAttribute{
				MarkdownDescription: "allow RTP answer to SRTP offer",
				Computed:            true,
			},
			"sip_early_offer_forced": schema.BoolAttribute{
				MarkdownDescription: "Forcefully Send Early-Offer",
				Computed:            true,
			},
			"sip_midcall_signaling_passthru": schema.BoolAttribute{
				MarkdownDescription: "Passthrough SIP messages from one IP leg to another IP leg",
				Computed:            true,
			},
			"sip_pass_thru_headers_unsupp": schema.BoolAttribute{
				MarkdownDescription: "Pass-through all unsupported headers",
				Computed:            true,
			},
			"sip_pass_thru_content_unsupp": schema.BoolAttribute{
				MarkdownDescription: "Pass-through all unsupported content",
				Computed:            true,
			},
			"sip_pass_thru_content_sdp": schema.StringAttribute{
				MarkdownDescription: "Set Pass-through sdp mode",
				Computed:            true,
			},
			"sip_audio_forced": schema.BoolAttribute{
				MarkdownDescription: "Allow only audio/fax, drop all other",
				Computed:            true,
			},
			"sip_localhost": schema.StringAttribute{
				MarkdownDescription: "Specify the DNS name for the localhost",
				Computed:            true,
			},
			"sip_bind_control_source_interface": schema.StringAttribute{
				MarkdownDescription: "GigabitEthernet IEEE 802.3z",
				Computed:            true,
			},
			"sip_bind_media_source_interface": schema.StringAttribute{
				MarkdownDescription: "GigabitEthernet IEEE 802.3z",
				Computed:            true,
			},
			"sip_bind_control_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: "Loopback interface",
				Computed:            true,
			},
			"sip_bind_media_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: "Loopback interface",
				Computed:            true,
			},
			"sip_bind_control_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: "Ten Gigabit Ethernet",
				Computed:            true,
			},
			"sip_bind_media_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: "Ten Gigabit Ethernet",
				Computed:            true,
			},
			"sip_bind_control_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: "Ethernet Channel of interfaces",
				Computed:            true,
			},
			"sip_bind_media_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: "Ethernet Channel of interfaces",
				Computed:            true,
			},
			"sip_contact_passing": schema.BoolAttribute{
				MarkdownDescription: "302 contact needs to be passed through for CFWD",
				Computed:            true,
			},
			"sip_requri_passing": schema.BoolAttribute{
				MarkdownDescription: "Request URI needs to be passed through",
				Computed:            true,
			},
			"sip_update_callerid": schema.BoolAttribute{
				MarkdownDescription: "Enable sending updates for callerid",
				Computed:            true,
			},
			"sip_anat": schema.BoolAttribute{
				MarkdownDescription: "Allow alternative network address types IPv4 and IPv6",
				Computed:            true,
			},
			"sip_g729_annexb_all": schema.BoolAttribute{
				MarkdownDescription: "g729b representing g729a and g729b to interop with CCM",
				Computed:            true,
			},
			"sip_privacy_policy_passthru": schema.BoolAttribute{
				MarkdownDescription: "Pass through privacy values received from peer leg",
				Computed:            true,
			},
			"sip_conn_reuse": schema.BoolAttribute{
				MarkdownDescription: "reuse the sip registration tcp connection for the end-point behind a Firewall",
				Computed:            true,
			},
			"sip_sip_profiles": schema.StringAttribute{
				MarkdownDescription: "The sip profiles tag number to be linked as global",
				Computed:            true,
			},
			"sip_sip_profiles_inbound": schema.StringAttribute{
				MarkdownDescription: "The sip profiles tag number to be linked as global",
				Computed:            true,
			},
		},
	}
}

func (d *VoiceServiceVoIPDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *VoiceServiceVoIPDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VoiceServiceVoIPData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
