// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &SIPUADataSource{}
	_ datasource.DataSourceWithConfigure = &SIPUADataSource{}
)

func NewSIPUADataSource() datasource.DataSource {
	return &SIPUADataSource{}
}

type SIPUADataSource struct {
	data *IosxeProviderData
}

func (d *SIPUADataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sip_ua"
}

func (d *SIPUADataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the SIP UA configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"transport_udp": schema.BoolAttribute{
				MarkdownDescription: "Enable SIP User Agent in UDP Mode",
				Computed:            true,
			},
			"transport_tcp": schema.BoolAttribute{
				MarkdownDescription: "Enable SIP User Agent in TCP Mode",
				Computed:            true,
			},
			"transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: "Enable SIP User Agent in TLS over TCP mode (Default: All TLS versions with fallback)",
				Computed:            true,
			},
			"sip_server": schema.StringAttribute{
				MarkdownDescription: "Configure a SIP Server Interface",
				Computed:            true,
			},
			"redirection": schema.BoolAttribute{
				MarkdownDescription: "Enable call redirection (3XX) handling",
				Computed:            true,
			},
			"remote_party_id": schema.BoolAttribute{
				MarkdownDescription: "Enable Remote-Party-ID support in SIP User Agent calls",
				Computed:            true,
			},
			"handle_replaces": schema.BoolAttribute{
				MarkdownDescription: "Handle INVITE with REPLACES header at SIP spi",
				Computed:            true,
			},
			"reason_header_override": schema.BoolAttribute{
				MarkdownDescription: "Enable Reason header to override SIP<->Q850 Mappings",
				Computed:            true,
			},
			"host_registrar": schema.BoolAttribute{
				MarkdownDescription: "Use sip-ua registrar value in Diversion and Contact header for 3xx messages",
				Computed:            true,
			},
			"max_forwards": schema.Int64Attribute{
				MarkdownDescription: "Change number of max-forwards for SIP Methods",
				Computed:            true,
			},
			"disable_early_media": schema.StringAttribute{
				MarkdownDescription: "Disable early-media cut through",
				Computed:            true,
			},
			"retry_invite": schema.Int64Attribute{
				MarkdownDescription: "INVITE retry value",
				Computed:            true,
			},
			"retry_register": schema.Int64Attribute{
				MarkdownDescription: "REGISTER retry value",
				Computed:            true,
			},
			"retry_rel1xx": schema.Int64Attribute{
				MarkdownDescription: "Reliable 1xx retry value",
				Computed:            true,
			},
			"retry_response": schema.Int64Attribute{
				MarkdownDescription: "Response retry value",
				Computed:            true,
			},
			"retry_keepalive": schema.Int64Attribute{
				MarkdownDescription: "KEEPALIVE retry value",
				Computed:            true,
			},
			"timers_expires": schema.Int64Attribute{
				MarkdownDescription: "Time to wait for the expiration of an INVITE request",
				Computed:            true,
			},
			"timers_trying": schema.Int64Attribute{
				MarkdownDescription: "Time to wait for provisional response to INVITE",
				Computed:            true,
			},
			"timers_connection_aging_tls": schema.Int64Attribute{
				MarkdownDescription: "TCP/UDP aging timer value in minutes",
				Computed:            true,
			},
			"timers_options": schema.Int64Attribute{
				MarkdownDescription: "Time to wait before OPTIONS retransmission",
				Computed:            true,
			},
			"timers_keepalive_active": schema.Int64Attribute{
				MarkdownDescription: "Time to wait between keepalive messages in active state",
				Computed:            true,
			},
			"timers_keepalive_down": schema.Int64Attribute{
				MarkdownDescription: "Time to wait between keepalive messages in down state",
				Computed:            true,
			},
			"connection_reuse": schema.BoolAttribute{
				MarkdownDescription: "Use listener port for sending requests over UDP",
				Computed:            true,
			},
			"connection_reuse_via_port": schema.BoolAttribute{
				MarkdownDescription: "Send responses to port present in Via header",
				Computed:            true,
			},
			"crypto_signaling_default_tls_profile": schema.StringAttribute{
				MarkdownDescription: "Associate a tls-profile",
				Computed:            true,
			},
			"crypto_signaling_remote_addrs": schema.ListNestedAttribute{
				MarkdownDescription: "Associate an IP network to a trustpoint",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"ipv4_address": schema.StringAttribute{
							MarkdownDescription: "Enter the IP address",
							Computed:            true,
						},
						"subnet_mask": schema.StringAttribute{
							MarkdownDescription: "Enter the mask",
							Computed:            true,
						},
						"tls_profile": schema.StringAttribute{
							MarkdownDescription: "Associate a tls-profile",
							Computed:            true,
						},
					},
				},
			},
			"authentication_username": schema.StringAttribute{
				MarkdownDescription: "name of the user authenticating",
				Computed:            true,
			},
			"authentication_password_type": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"authentication_password": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
				Sensitive:           true,
			},
			"authentication_realm_username": schema.StringAttribute{
				MarkdownDescription: "name of the user authenticating",
				Computed:            true,
			},
			"authentication_realm_password": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
				Sensitive:           true,
			},
			"authentication_realm": schema.StringAttribute{
				MarkdownDescription: "Realm at which the credentials are applicable",
				Computed:            true,
			},
			"credentials_numbers": schema.ListNestedAttribute{
				MarkdownDescription: "",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"number": schema.StringAttribute{
							MarkdownDescription: "number which is getting registered",
							Computed:            true,
						},
						"username": schema.StringAttribute{
							MarkdownDescription: "name of the user authenticating",
							Computed:            true,
						},
						"password_type": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
						},
						"password": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
							Sensitive:           true,
						},
						"realm": schema.StringAttribute{
							MarkdownDescription: "Realm at which the credentials are applicable",
							Computed:            true,
						},
					},
				},
			},
			"credentials_usernames": schema.ListNestedAttribute{
				MarkdownDescription: "",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"username": schema.StringAttribute{
							MarkdownDescription: "name of the user authenticating",
							Computed:            true,
						},
						"password_type": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
						},
						"password": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
							Sensitive:           true,
						},
						"realm": schema.StringAttribute{
							MarkdownDescription: "Realm at which the credentials are applicable",
							Computed:            true,
						},
					},
				},
			},
			"credentials_dhcp_password_type": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"credentials_dhcp_password": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
				Sensitive:           true,
			},
			"credentials_dhcp_realm": schema.StringAttribute{
				MarkdownDescription: "Realm at which the credentials are applicable",
				Computed:            true,
			},
			"registrar_primary": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"registrar_primary_expires": schema.Int64Attribute{
				MarkdownDescription: "Default registration expires time",
				Computed:            true,
			},
			"registrar_primary_scheme": schema.StringAttribute{
				MarkdownDescription: "URL scheme - sips or sip",
				Computed:            true,
			},
			"registrar_primary_tcp": schema.BoolAttribute{
				MarkdownDescription: "Use TCP as Transport Layer Protocol (default: UDP)",
				Computed:            true,
			},
			"registrar_primary_tls": schema.BoolAttribute{
				MarkdownDescription: "Use TLS encryption over TCP Transport Layer Protocol",
				Computed:            true,
			},
			"registrar_primary_refresh_ratio": schema.Int64Attribute{
				MarkdownDescription: "Default registration refresh ratio",
				Computed:            true,
			},
			"registrar_secondary": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"registrar_secondary_expires": schema.Int64Attribute{
				MarkdownDescription: "Default registration expires time",
				Computed:            true,
			},
			"registrar_dhcp": schema.BoolAttribute{
				MarkdownDescription: "Registrar Server address provision via DHCP",
				Computed:            true,
			},
			"registrars": schema.ListNestedAttribute{
				MarkdownDescription: "Registrar Index Value for configuring multiple registrars",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							MarkdownDescription: "Specify the rule tag",
							Computed:            true,
						},
						"registrar": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
						},
						"expires": schema.Int64Attribute{
							MarkdownDescription: "Default registration expires time",
							Computed:            true,
						},
						"scheme": schema.StringAttribute{
							MarkdownDescription: "URL scheme - sips or sip",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *SIPUADataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *SIPUADataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config SIPUAData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
