// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &VoiceClassTLSProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &VoiceClassTLSProfileDataSource{}
)

func NewVoiceClassTLSProfileDataSource() datasource.DataSource {
	return &VoiceClassTLSProfileDataSource{}
}

type VoiceClassTLSProfileDataSource struct {
	data *IosxeProviderData
}

func (d *VoiceClassTLSProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voice_class_tls_profile"
}

func (d *VoiceClassTLSProfileDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Voice Class TLS Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"tag": schema.Int64Attribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Define the description of input options",
				Computed:            true,
			},
			"trustpoint": schema.StringAttribute{
				MarkdownDescription: "Define the trustpoint name",
				Computed:            true,
			},
			"client_vtp": schema.StringAttribute{
				MarkdownDescription: "Set Client Verification Trustpoint",
				Computed:            true,
			},
			"cn_san_validate_server": schema.BoolAttribute{
				MarkdownDescription: "Enable CN/SAN validation for server certificate",
				Computed:            true,
			},
			"cn_san_validate_client": schema.BoolAttribute{
				MarkdownDescription: "Enable CN/SAN validation for client certificate",
				Computed:            true,
			},
			"cn_san_validate_bidirectional": schema.BoolAttribute{
				MarkdownDescription: "Enable CN/SAN validation for both client and server certificate",
				Computed:            true,
			},
			"cn_san_names": schema.ListNestedAttribute{
				MarkdownDescription: "Specify the tag of CN/SAN hostname/pattern list entry",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"tag": schema.Int64Attribute{
							MarkdownDescription: "",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Specify the CN/SAN hostname/pattern, valid values are a FQDN or *.<domain-name>",
							Computed:            true,
						},
					},
				},
			},
			"strict_cipher": schema.BoolAttribute{
				MarkdownDescription: "Use only ciphers use by SIP standards",
				Computed:            true,
			},
			"tls_cipher_id": schema.StringAttribute{
				MarkdownDescription: "Specify tls-cipher list tag",
				Computed:            true,
			},
			"sni_send": schema.BoolAttribute{
				MarkdownDescription: "Include SNI extension in outbound TLS connections",
				Computed:            true,
			},
		},
	}
}

func (d *VoiceClassTLSProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *VoiceClassTLSProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VoiceClassTLSProfileData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
