// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &VoiceDSPFarmProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &VoiceDSPFarmProfileDataSource{}
)

func NewVoiceDSPFarmProfileDataSource() datasource.DataSource {
	return &VoiceDSPFarmProfileDataSource{}
}

type VoiceDSPFarmProfileDataSource struct {
	data *IosxeProviderData
}

func (d *VoiceDSPFarmProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voice_dspfarm_profile"
}

func (d *VoiceDSPFarmProfileDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Voice DSPFarm Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"tag": schema.Int64Attribute{
				MarkdownDescription: "dspfarm profile ID",
				Required:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Configure the profile types",
				Computed:            true,
			},
			"universal": schema.BoolAttribute{
				MarkdownDescription: "Configure the transcode universal profile type",
				Computed:            true,
			},
			"security": schema.BoolAttribute{
				MarkdownDescription: "Enable security for the dspfarm service",
				Computed:            true,
			},
			"trustpoint": schema.StringAttribute{
				MarkdownDescription: "trustpoint label to use with this profile",
				Computed:            true,
			},
			"codec_g711ulaw": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g711ulaw",
				Computed:            true,
			},
			"codec_g711alaw": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g711alaw",
				Computed:            true,
			},
			"codec_g722_64": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g722-64",
				Computed:            true,
			},
			"codec_g729ar8": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g729ar8",
				Computed:            true,
			},
			"codec_g729abr8": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g729abr8",
				Computed:            true,
			},
			"codec_g729br8": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g729br8",
				Computed:            true,
			},
			"codec_g729r8": schema.BoolAttribute{
				MarkdownDescription: "Add the codec g729r8",
				Computed:            true,
			},
			"codec_ilbc": schema.BoolAttribute{
				MarkdownDescription: "Add the codec ilbc",
				Computed:            true,
			},
			"codec_opus": schema.BoolAttribute{
				MarkdownDescription: "Add the codec opus",
				Computed:            true,
			},
			"codec_pass_through": schema.BoolAttribute{
				MarkdownDescription: "Add the codec pass-through",
				Computed:            true,
			},
			"associate_application": schema.StringAttribute{
				MarkdownDescription: "Configure the application to associate",
				Computed:            true,
			},
			"codec_isac": schema.BoolAttribute{
				MarkdownDescription: "Add the codec isac",
				Computed:            true,
			},
			"maximum_sessions": schema.Int64Attribute{
				MarkdownDescription: "Configure the maximum sessions of transcode or conference profile",
				Computed:            true,
			},
			"maximum_mtp_sessions_hardware": schema.Int64Attribute{
				MarkdownDescription: "Configure the maximum hardware MTP sessions of this profile",
				Computed:            true,
			},
			"maximum_mtp_sessions_software": schema.Int64Attribute{
				MarkdownDescription: "Configure the maximum software MTP sessions of this profile",
				Computed:            true,
			},
			"conference_participants": schema.StringAttribute{
				MarkdownDescription: "Configure the maximum number of conferee per conference session",
				Computed:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: "Shutdown or bring up the profile",
				Computed:            true,
			},
		},
	}
}

func (d *VoiceDSPFarmProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *VoiceDSPFarmProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VoiceDSPFarmProfileData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
