// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeVoiceClassTenant(t *testing.T) {
	if os.Getenv("C8000V") == "" {
		t.Skip("skipping test, set environment variable C8000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "session_transport_tcp_tls", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "localhost", "dns:cube.example.com"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "header_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "error_passthru", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "referto_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "contact_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "requri_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "update_callerid", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "redirection", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "random_contact", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "anat", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "override_hostname", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "url_sips", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "rel1xx_disable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "early_offer_forced", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "privacy_policy_passthru", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "block_183_sdp", "present"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "pass_thru_content_custom_sdp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "audio_forced", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "connection_reuse", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "connection_reuse_via_port", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "handle_replaces", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "reason_header_override", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "host_registrar", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "max_forwards", "70"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "g729_annexb_override", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "disable_early_media", "180"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "asserted_id_pai", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "asymmetric_payload_full", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "midcall_signaling_passthru", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "srtp_negotiate_cisco", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "conn_reuse", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "options_ping_interval", "60"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "pass_thru_headers_unsupp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_class_tenant.test", "pass_thru_content_unsupp", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeVoiceClassTenantPrerequisitesConfig + testAccDataSourceIosxeVoiceClassTenantConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceIosxeVoiceClassTenantPrerequisitesConfig = `
resource "iosxe_yang" "PreReq0" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/service[type=voip]"
	delete = false
	attributes = {
		"type" = "voip"
		"allow-connections/sip/to/sip" = ""
	}
}

resource "iosxe_yang" "PreReq1" {
	path = ""
	attributes = {
	}
}

resource "iosxe_yang" "PreReq2" {
	path = ""
	attributes = {
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeVoiceClassTenantConfig() string {
	config := `resource "iosxe_voice_class_tenant" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	tag = 100` + "\n"
	config += `	session_transport_tcp_tls = true` + "\n"
	config += `	localhost = "dns:cube.example.com"` + "\n"
	config += `	header_passing = true` + "\n"
	config += `	error_passthru = true` + "\n"
	config += `	referto_passing = true` + "\n"
	config += `	contact_passing = true` + "\n"
	config += `	requri_passing = true` + "\n"
	config += `	update_callerid = true` + "\n"
	config += `	redirection = true` + "\n"
	config += `	random_contact = true` + "\n"
	config += `	anat = false` + "\n"
	config += `	override_hostname = false` + "\n"
	config += `	url_sips = true` + "\n"
	config += `	rel1xx_disable = true` + "\n"
	config += `	early_offer_forced = true` + "\n"
	config += `	privacy_policy_passthru = true` + "\n"
	config += `	block_183_sdp = "present"` + "\n"
	config += `	pass_thru_content_custom_sdp = true` + "\n"
	config += `	audio_forced = true` + "\n"
	config += `	connection_reuse = true` + "\n"
	config += `	connection_reuse_via_port = true` + "\n"
	config += `	handle_replaces = true` + "\n"
	config += `	reason_header_override = true` + "\n"
	config += `	host_registrar = true` + "\n"
	config += `	max_forwards = 70` + "\n"
	config += `	g729_annexb_override = true` + "\n"
	config += `	disable_early_media = "180"` + "\n"
	config += `	asserted_id_pai = true` + "\n"
	config += `	asymmetric_payload_full = true` + "\n"
	config += `	midcall_signaling_passthru = true` + "\n"
	config += `	srtp_negotiate_cisco = true` + "\n"
	config += `	conn_reuse = true` + "\n"
	config += `	options_ping_interval = 60` + "\n"
	config += `	pass_thru_headers_unsupp = true` + "\n"
	config += `	pass_thru_content_unsupp = true` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, iosxe_yang.PreReq1, iosxe_yang.PreReq2, ]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_voice_class_tenant" "test" {
			tag = 100
			depends_on = [iosxe_voice_class_tenant.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
