// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeDialPeerVoice(t *testing.T) {
	if os.Getenv("C8000V") == "" {
		t.Skip("skipping test, set environment variable C8000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "type", "voip"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "description", "Outbound to CUCM"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "preference", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "huntstop", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "shutdown", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "vad", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "session_protocol", "sipv2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "session_server_group", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "voice_class_sip_options_keepalive_profile", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "destination_dpg", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "voice_class_sip_tenant", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dial_peer_voice.test", "voice_class_sip_profiles", "100"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeDialPeerVoicePrerequisitesConfig + testAccDataSourceIosxeDialPeerVoiceConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceIosxeDialPeerVoicePrerequisitesConfig = `
resource "iosxe_yang" "PreReq0" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/service[type=voip]"
	delete = false
	attributes = {
		"type" = "voip"
		"allow-connections/sip/to/sip" = ""
	}
}

resource "iosxe_yang" "PreReq1" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/dpg[id=100]"
	attributes = {
		"id" = "100"
	}
}

resource "iosxe_yang" "PreReq2" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/server-group[id=10]"
	attributes = {
		"id" = "10"
	}
}

resource "iosxe_yang" "PreReq3" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-options-keepalive[id=100]"
	attributes = {
		"id" = "100"
	}
}

resource "iosxe_yang" "PreReq4" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/tenant[id=100]"
	attributes = {
		"id" = "100"
	}
}

resource "iosxe_yang" "PreReq5" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-profiles[id=100]"
	attributes = {
		"id" = "100"
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeDialPeerVoiceConfig() string {
	config := `resource "iosxe_dial_peer_voice" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	tag = 100` + "\n"
	config += `	type = "voip"` + "\n"
	config += `	description = "Outbound to CUCM"` + "\n"
	config += `	preference = 1` + "\n"
	config += `	huntstop = false` + "\n"
	config += `	shutdown = false` + "\n"
	config += `	vad = true` + "\n"
	config += `	session_protocol = "sipv2"` + "\n"
	config += `	session_server_group = "10"` + "\n"
	config += `	voice_class_sip_options_keepalive_profile = "100"` + "\n"
	config += `	destination_dpg = "100"` + "\n"
	config += `	voice_class_sip_tenant = "100"` + "\n"
	config += `	voice_class_sip_profiles = "100"` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, iosxe_yang.PreReq1, iosxe_yang.PreReq2, iosxe_yang.PreReq3, iosxe_yang.PreReq4, iosxe_yang.PreReq5, ]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_dial_peer_voice" "test" {
			tag = 100
			depends_on = [iosxe_dial_peer_voice.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
