// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &DialPeerVoiceDataSource{}
	_ datasource.DataSourceWithConfigure = &DialPeerVoiceDataSource{}
)

func NewDialPeerVoiceDataSource() datasource.DataSource {
	return &DialPeerVoiceDataSource{}
}

type DialPeerVoiceDataSource struct {
	data *IosxeProviderData
}

func (d *DialPeerVoiceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dial_peer_voice"
}

func (d *DialPeerVoiceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Dial Peer Voice configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"tag": schema.Int64Attribute{
				MarkdownDescription: "Voice dial-peer tag",
				Required:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Dial peer type",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Dial peer specific description",
				Computed:            true,
			},
			"destination_pattern": schema.StringAttribute{
				MarkdownDescription: "A full E.164 telephone number prefix",
				Computed:            true,
			},
			"preference": schema.Int64Attribute{
				MarkdownDescription: "Configure the preference order of this dial-peer",
				Computed:            true,
			},
			"huntstop": schema.BoolAttribute{
				MarkdownDescription: "Stop hunting on Dial-Peers",
				Computed:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: "Change the Admin State of this peer to down",
				Computed:            true,
			},
			"vad": schema.BoolAttribute{
				MarkdownDescription: "Use vad as necessary option",
				Computed:            true,
			},
			"srtp": schema.BoolAttribute{
				MarkdownDescription: "Allow Secure calls",
				Computed:            true,
			},
			"session_protocol": schema.StringAttribute{
				MarkdownDescription: "The session protocol to be used in getting to this peer",
				Computed:            true,
			},
			"session_server_group": schema.StringAttribute{
				MarkdownDescription: "Configure voice class server-group",
				Computed:            true,
			},
			"session_target": schema.StringAttribute{
				MarkdownDescription: "WORD A string specifying the session target",
				Computed:            true,
			},
			"session_transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - TLS over TCP",
				Computed:            true,
			},
			"session_transport_tcp": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - TCP",
				Computed:            true,
			},
			"session_transport_udp": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - UDP",
				Computed:            true,
			},
			"voice_class_sip_options_keepalive_profile": schema.StringAttribute{
				MarkdownDescription: "Consolidate Options Keepalive profile setup",
				Computed:            true,
			},
			"incoming_called_number": schema.StringAttribute{
				MarkdownDescription: "An incoming called number pattern",
				Computed:            true,
			},
			"incoming_called_e164_pattern_map": schema.StringAttribute{
				MarkdownDescription: "Configure voice class to match destination e164-pattern-map",
				Computed:            true,
			},
			"incoming_uri_via": schema.StringAttribute{
				MarkdownDescription: "Match incoming topmost Via header",
				Computed:            true,
			},
			"incoming_uri_request": schema.StringAttribute{
				MarkdownDescription: "Match incoming Request-URI",
				Computed:            true,
			},
			"destination_dpg": schema.StringAttribute{
				MarkdownDescription: "Configure voice class dpg",
				Computed:            true,
			},
			"destination_e164_pattern_map": schema.StringAttribute{
				MarkdownDescription: "Configure voice class to match destination e164-pattern-map",
				Computed:            true,
			},
			"destination_uri": schema.StringAttribute{
				MarkdownDescription: "Configure voice class to match destination URI",
				Computed:            true,
			},
			"translation_profile_incoming": schema.StringAttribute{
				MarkdownDescription: "Translation Profile for incoming call leg",
				Computed:            true,
			},
			"translation_profile_outgoing": schema.StringAttribute{
				MarkdownDescription: "Translation Profile for outgoing call leg",
				Computed:            true,
			},
			"voice_class_sip_tenant": schema.StringAttribute{
				MarkdownDescription: "Set SIP-Tenant parameters",
				Computed:            true,
			},
			"voice_class_sip_profiles": schema.StringAttribute{
				MarkdownDescription: "The sip profiles tag number to be linked as global",
				Computed:            true,
			},
			"voice_class_sip_profiles_inbound": schema.StringAttribute{
				MarkdownDescription: "The sip profiles tag number to be linked as global",
				Computed:            true,
			},
			"voice_class_sip_profiles_inbound_enable": schema.BoolAttribute{
				MarkdownDescription: "Turn on inbound SIP profiles feature",
				Computed:            true,
			},
			"voice_class_sip_bind_control_source_interface": schema.StringAttribute{
				MarkdownDescription: "GigabitEthernet IEEE 802.3z",
				Computed:            true,
			},
			"voice_class_sip_bind_media_source_interface": schema.StringAttribute{
				MarkdownDescription: "GigabitEthernet IEEE 802.3z",
				Computed:            true,
			},
			"voice_class_sip_bind_control_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: "Loopback interface",
				Computed:            true,
			},
			"voice_class_sip_bind_media_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: "Loopback interface",
				Computed:            true,
			},
			"voice_class_sip_bind_control_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: "Ten Gigabit Ethernet",
				Computed:            true,
			},
			"voice_class_sip_bind_media_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: "Ten Gigabit Ethernet",
				Computed:            true,
			},
			"voice_class_sip_bind_control_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: "Ethernet Channel of interfaces",
				Computed:            true,
			},
			"voice_class_sip_bind_media_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: "Ethernet Channel of interfaces",
				Computed:            true,
			},
			"voice_class_sip_early_offer_forced": schema.BoolAttribute{
				MarkdownDescription: "Forcefully Send Early-Offer",
				Computed:            true,
			},
			"voice_class_codec": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"voice_class_codec_offer_all": schema.BoolAttribute{
				MarkdownDescription: "Offer All the codec configured in this voice-class codec",
				Computed:            true,
			},
			"voice_class_stun_usage": schema.StringAttribute{
				MarkdownDescription: "Set stun usage tag",
				Computed:            true,
			},
			"dtmf_relay_rtp_nte": schema.BoolAttribute{
				MarkdownDescription: "RTP Named Telephone Event RFC 2833",
				Computed:            true,
			},
			"dtmf_relay_sip_info": schema.BoolAttribute{
				MarkdownDescription: "Relay via SIP INFO messages",
				Computed:            true,
			},
			"dtmf_relay_sip_kpml": schema.BoolAttribute{
				MarkdownDescription: "Relay over SIP SUBSCRIBE/NOTIFY",
				Computed:            true,
			},
			"dtmf_relay_sip_notify": schema.BoolAttribute{
				MarkdownDescription: "Relay via SIP NOTIFY messages",
				Computed:            true,
			},
			"ip_qos_dscp_signaling": schema.StringAttribute{
				MarkdownDescription: "Specify ip DSCP",
				Computed:            true,
			},
			"ip_qos_dscp_signaling_enable": schema.BoolAttribute{
				MarkdownDescription: "Apply DSCP to signaling packets",
				Computed:            true,
			},
			"max_conn": schema.Int64Attribute{
				MarkdownDescription: "Maximum connections, negation sets to unlimited",
				Computed:            true,
			},
			"max_conn_exempt_local_media": schema.BoolAttribute{
				MarkdownDescription: "max-conn value will not be updated for local media calls",
				Computed:            true,
			},
			"answer_address": schema.StringAttribute{
				MarkdownDescription: "The Call Destination Number",
				Computed:            true,
			},
			"codec_transparent": schema.BoolAttribute{
				MarkdownDescription: "Uses the endpoint codec",
				Computed:            true,
			},
			"media_class": schema.StringAttribute{
				MarkdownDescription: "Set Dial-peer media class",
				Computed:            true,
			},
			"voice_class_media": schema.StringAttribute{
				MarkdownDescription: "Set media parameters for call",
				Computed:            true,
			},
			"corlist_incoming": schema.StringAttribute{
				MarkdownDescription: "set the incoming Class of Restriction lists",
				Computed:            true,
			},
			"corlist_outgoing": schema.StringAttribute{
				MarkdownDescription: "set the outgoing Class of Restriction lists",
				Computed:            true,
			},
			"direct_inward_dial": schema.BoolAttribute{
				MarkdownDescription: "Use Called Number as final call destination",
				Computed:            true,
			},
			"forward_digits_all": schema.BoolAttribute{
				MarkdownDescription: "Forward all destination digits",
				Computed:            true,
			},
			"forward_digits_num": schema.Int64Attribute{
				MarkdownDescription: "Number of right-justified dial digits to be forwarded",
				Computed:            true,
			},
			"port": schema.StringAttribute{
				MarkdownDescription: "Voice port associated with this peer",
				Computed:            true,
			},
			"prefix": schema.StringAttribute{
				MarkdownDescription: "The pattern to be appended before the dial num",
				Computed:            true,
			},
			"trunk_groups": schema.ListNestedAttribute{
				MarkdownDescription: "trunk groups associated with this peer",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "Trunk group ID",
							Computed:            true,
						},
						"preference": schema.Int64Attribute{
							MarkdownDescription: "trunk group preference value",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *DialPeerVoiceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *DialPeerVoiceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DialPeerVoiceData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
