// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeVoiceRegisterPool(t *testing.T) {
	if os.Getenv("C8000V") == "" {
		t.Skip("skipping test, set environment variable C8000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "id_network_address", "192.0.2.0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "id_network_mask", "255.255.255.0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "call_forward_b2bua_all", "1001"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "call_forward_b2bua_busy", "1001"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "call_forward_b2bua_mailbox", "1001"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "call_forward_b2bua_noan", "1001"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "call_forward_b2bua_noan_timeout", "20"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "dtmf_relay_rtp_nte", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "dtmf_relay_sip_kpml", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_voice_register_pool.test", "dtmf_relay_sip_notify", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeVoiceRegisterPoolPrerequisitesConfig + testAccDataSourceIosxeVoiceRegisterPoolConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceIosxeVoiceRegisterPoolPrerequisitesConfig = `
resource "iosxe_yang" "PreReq0" {
	path = "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/register/global"
	attributes = {
		"max-pool" = "10"
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeVoiceRegisterPoolConfig() string {
	config := `resource "iosxe_voice_register_pool" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	tag = 1` + "\n"
	config += `	id_network_address = "192.0.2.0"` + "\n"
	config += `	id_network_mask = "255.255.255.0"` + "\n"
	config += `	call_forward_b2bua_all = "1001"` + "\n"
	config += `	call_forward_b2bua_busy = "1001"` + "\n"
	config += `	call_forward_b2bua_mailbox = "1001"` + "\n"
	config += `	call_forward_b2bua_noan = "1001"` + "\n"
	config += `	call_forward_b2bua_noan_timeout = 20` + "\n"
	config += `	dtmf_relay_rtp_nte = true` + "\n"
	config += `	dtmf_relay_sip_kpml = true` + "\n"
	config += `	dtmf_relay_sip_notify = true` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, ]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_voice_register_pool" "test" {
			tag = 1
			depends_on = [iosxe_voice_register_pool.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
