// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &VoiceClassSIPOptionsKeepaliveDataSource{}
	_ datasource.DataSourceWithConfigure = &VoiceClassSIPOptionsKeepaliveDataSource{}
)

func NewVoiceClassSIPOptionsKeepaliveDataSource() datasource.DataSource {
	return &VoiceClassSIPOptionsKeepaliveDataSource{}
}

type VoiceClassSIPOptionsKeepaliveDataSource struct {
	data *IosxeProviderData
}

func (d *VoiceClassSIPOptionsKeepaliveDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voice_class_sip_options_keepalive"
}

func (d *VoiceClassSIPOptionsKeepaliveDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Voice Class SIP Options Keepalive configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"tag": schema.Int64Attribute{
				MarkdownDescription: "Voice class sip-options-keepalive tag",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of a options-keepalive profile",
				Computed:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: "Put sip-options-keepalive to inactive state",
				Computed:            true,
			},
			"up_interval": schema.Int64Attribute{
				MarkdownDescription: "OPTIONS keepalive timer interval for UP endpoint",
				Computed:            true,
			},
			"down_interval": schema.Int64Attribute{
				MarkdownDescription: "OPTIONS keepalive timer interval for DOWN endpoint",
				Computed:            true,
			},
			"retry": schema.Int64Attribute{
				MarkdownDescription: "Retry count for OPTIONS keepalive retransmission",
				Computed:            true,
			},
			"sip_profiles": schema.StringAttribute{
				MarkdownDescription: "Voice Class SIP Profiles",
				Computed:            true,
			},
			"transport_udp": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - UDP",
				Computed:            true,
			},
			"transport_tcp": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - TCP",
				Computed:            true,
			},
			"transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: "Transport Layer Protocol - TLS over TCP",
				Computed:            true,
			},
		},
	}
}

func (d *VoiceClassSIPOptionsKeepaliveDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *VoiceClassSIPOptionsKeepaliveDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VoiceClassSIPOptionsKeepaliveData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
