// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type Controller struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	Type              types.String `tfsdk:"type"`
	Number            types.String `tfsdk:"number"`
	Framing           types.String `tfsdk:"framing"`
	E1Framing         types.String `tfsdk:"e1_framing"`
	PriGroupTimeslots types.String `tfsdk:"pri_group_timeslots"`
}

type ControllerData struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	Type              types.String `tfsdk:"type"`
	Number            types.String `tfsdk:"number"`
	Framing           types.String `tfsdk:"framing"`
	E1Framing         types.String `tfsdk:"e1_framing"`
	PriGroupTimeslots types.String `tfsdk:"pri_group_timeslots"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data Controller) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/controller/Cisco-IOS-XE-controller:controller-tx-ex-list=%v,%v", url.QueryEscape(fmt.Sprintf("%v", data.Type.ValueString())), url.QueryEscape(fmt.Sprintf("%v", data.Number.ValueString())))
}

func (data ControllerData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/controller/Cisco-IOS-XE-controller:controller-tx-ex-list=%v,%v", url.QueryEscape(fmt.Sprintf("%v", data.Type.ValueString())), url.QueryEscape(fmt.Sprintf("%v", data.Number.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data Controller) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/controller/Cisco-IOS-XE-controller:controller-tx-ex-list[name=%v][number=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Type.ValueString()), fmt.Sprintf("%v", data.Number.ValueString()))
	return path
}

func (data ControllerData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/controller/Cisco-IOS-XE-controller:controller-tx-ex-list[name=%v][number=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Type.ValueString()), fmt.Sprintf("%v", data.Number.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data Controller) toBodyXML(ctx context.Context, config Controller) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data Controller) addToBodyXML(ctx context.Context, config Controller, body netconf.Body) netconf.Body {
	if !data.Type.IsNull() && !data.Type.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/name", data.Type.ValueString())
	}
	if !data.Number.IsNull() && !data.Number.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/number", data.Number.ValueString())
	}
	if !data.Framing.IsNull() && !data.Framing.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/framing-config/tx-framing", data.Framing.ValueString())
	}
	if !data.E1Framing.IsNull() && !data.E1Framing.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/framing-config/e1-framing", data.E1Framing.ValueString())
	}
	if !data.PriGroupTimeslots.IsNull() && !data.PriGroupTimeslots.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/pri-group/timeslots", data.PriGroupTimeslots.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *Controller) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/name"); value.Exists() && !data.Type.IsNull() {
		data.Type = types.StringValue(value.String())
	} else {
		data.Type = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/number"); value.Exists() && !data.Number.IsNull() {
		data.Number = types.StringValue(value.String())
	} else {
		data.Number = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/tx-framing"); value.Exists() && !data.Framing.IsNull() {
		data.Framing = types.StringValue(value.String())
	} else {
		data.Framing = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/e1-framing"); value.Exists() && !data.E1Framing.IsNull() {
		data.E1Framing = types.StringValue(value.String())
	} else {
		data.E1Framing = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pri-group/timeslots"); value.Exists() && !data.PriGroupTimeslots.IsNull() {
		data.PriGroupTimeslots = types.StringValue(value.String())
	} else {
		data.PriGroupTimeslots = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *Controller) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/tx-framing"); value.Exists() {
		data.Framing = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/e1-framing"); value.Exists() {
		data.E1Framing = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pri-group/timeslots"); value.Exists() {
		data.PriGroupTimeslots = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *ControllerData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/tx-framing"); value.Exists() {
		data.Framing = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/framing-config/e1-framing"); value.Exists() {
		data.E1Framing = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pri-group/timeslots"); value.Exists() {
		data.PriGroupTimeslots = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *Controller) addDeletedItemsXML(ctx context.Context, state Controller, body string) string {
	b := netconf.NewBody(body)
	if !state.PriGroupTimeslots.IsNull() && data.PriGroupTimeslots.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/pri-group/timeslots")
	}
	if !state.E1Framing.IsNull() && data.E1Framing.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/framing-config/e1-framing")
	}
	if !state.Framing.IsNull() && data.Framing.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/framing-config/tx-framing")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *Controller) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.PriGroupTimeslots.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/pri-group/timeslots")
	}
	if !data.E1Framing.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/framing-config/e1-framing")
	}
	if !data.Framing.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/framing-config/tx-framing")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
