// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassTLSCipher struct {
	Device     types.String                 `tfsdk:"device"`
	Id         types.String                 `tfsdk:"id"`
	DeleteMode types.String                 `tfsdk:"delete_mode"`
	Tag        types.Int64                  `tfsdk:"tag"`
	Ciphers    []VoiceClassTLSCipherCiphers `tfsdk:"ciphers"`
}
type VoiceClassTLSCipherCiphers struct {
	Preference  types.Int64  `tfsdk:"preference"`
	CipherSuite types.String `tfsdk:"cipher_suite"`
}

type VoiceClassTLSCipherData struct {
	Device  types.String                     `tfsdk:"device"`
	Id      types.String                     `tfsdk:"id"`
	Tag     types.Int64                      `tfsdk:"tag"`
	Ciphers []VoiceClassTLSCipherCiphersData `tfsdk:"ciphers"`
}
type VoiceClassTLSCipherCiphersData struct {
	Preference  types.Int64  `tfsdk:"preference"`
	CipherSuite types.String `tfsdk:"cipher_suite"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassTLSCipher) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/tls-cipher=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassTLSCipherData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/tls-cipher=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassTLSCipher) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/tls-cipher[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassTLSCipherData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/tls-cipher[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassTLSCipher) toBodyXML(ctx context.Context, config VoiceClassTLSCipher) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassTLSCipher) addToBodyXML(ctx context.Context, config VoiceClassTLSCipher, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if len(data.Ciphers) > 0 {
		for _, item := range data.Ciphers {
			cBody := netconf.Body{}
			if !item.Preference.IsNull() && !item.Preference.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "preference", strconv.FormatInt(item.Preference.ValueInt64(), 10))
			}
			if !item.CipherSuite.IsNull() && !item.CipherSuite.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "type", item.CipherSuite.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/cipher", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassTLSCipher) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	for i := range data.Ciphers {
		keys := [...]string{"preference"}
		keyValues := [...]string{strconv.FormatInt(data.Ciphers[i].Preference.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/cipher").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "preference"); value.Exists() && !data.Ciphers[i].Preference.IsNull() {
			data.Ciphers[i].Preference = types.Int64Value(value.Int())
		} else {
			data.Ciphers[i].Preference = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "type"); value.Exists() && !data.Ciphers[i].CipherSuite.IsNull() {
			data.Ciphers[i].CipherSuite = types.StringValue(value.String())
		} else {
			data.Ciphers[i].CipherSuite = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassTLSCipher) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/cipher"); value.Exists() {
		data.Ciphers = make([]VoiceClassTLSCipherCiphers, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassTLSCipherCiphers{}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "type"); cValue.Exists() {
				item.CipherSuite = types.StringValue(cValue.String())
			}
			data.Ciphers = append(data.Ciphers, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassTLSCipherData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/cipher"); value.Exists() {
		data.Ciphers = make([]VoiceClassTLSCipherCiphersData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassTLSCipherCiphersData{}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "type"); cValue.Exists() {
				item.CipherSuite = types.StringValue(cValue.String())
			}
			data.Ciphers = append(data.Ciphers, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassTLSCipher) addDeletedItemsXML(ctx context.Context, state VoiceClassTLSCipher, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Ciphers {
		stateKeys := [...]string{"preference"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Ciphers[i].Preference.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Ciphers[i].Preference.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Ciphers {
			found = true
			if state.Ciphers[i].Preference.ValueInt64() != data.Ciphers[j].Preference.ValueInt64() {
				found = false
			}
			if found {
				if !state.Ciphers[i].CipherSuite.IsNull() && data.Ciphers[j].CipherSuite.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/cipher%v/type", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/cipher%v", predicates))
		}
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassTLSCipher) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Ciphers {
		keys := [...]string{"preference"}
		keyValues := [...]string{strconv.FormatInt(data.Ciphers[i].Preference.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/cipher%v", predicates))
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
