// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassURI struct {
	Device       types.String `tfsdk:"device"`
	Id           types.String `tfsdk:"id"`
	DeleteMode   types.String `tfsdk:"delete_mode"`
	Tag          types.String `tfsdk:"tag"`
	Type         types.String `tfsdk:"type"`
	Pattern      types.String `tfsdk:"pattern"`
	Hosts        types.List   `tfsdk:"hosts"`
	UserId       types.String `tfsdk:"user_id"`
	PhoneContext types.String `tfsdk:"phone_context"`
	PhoneNumber  types.String `tfsdk:"phone_number"`
}

type VoiceClassURIData struct {
	Device       types.String `tfsdk:"device"`
	Id           types.String `tfsdk:"id"`
	Tag          types.String `tfsdk:"tag"`
	Type         types.String `tfsdk:"type"`
	Pattern      types.String `tfsdk:"pattern"`
	Hosts        types.List   `tfsdk:"hosts"`
	UserId       types.String `tfsdk:"user_id"`
	PhoneContext types.String `tfsdk:"phone_context"`
	PhoneNumber  types.String `tfsdk:"phone_number"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassURI) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/uri/uri=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueString())))
}

func (data VoiceClassURIData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/uri/uri=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassURI) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/uri/uri[uritag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueString()))
	return path
}

func (data VoiceClassURIData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/uri/uri[uritag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassURI) toBodyXML(ctx context.Context, config VoiceClassURI) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassURI) addToBodyXML(ctx context.Context, config VoiceClassURI, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/uritag", data.Tag.ValueString())
	}
	if !data.Type.IsNull() && !data.Type.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/type", data.Type.ValueString())
	}
	if !data.Pattern.IsNull() && !data.Pattern.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/pattern", data.Pattern.ValueString())
	}
	if !data.Hosts.IsNull() && !data.Hosts.IsUnknown() {
		var values []string
		data.Hosts.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/host", v)
		}
	}
	if !data.UserId.IsNull() && !data.UserId.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-id", data.UserId.ValueString())
	}
	if !data.PhoneContext.IsNull() && !data.PhoneContext.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/phone/context", data.PhoneContext.ValueString())
	}
	if !data.PhoneNumber.IsNull() && !data.PhoneNumber.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/phone/number", data.PhoneNumber.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassURI) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/uritag"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.StringValue(value.String())
	} else {
		data.Tag = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() && !data.Type.IsNull() {
		data.Type = types.StringValue(value.String())
	} else {
		data.Type = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pattern"); value.Exists() && !data.Pattern.IsNull() {
		data.Pattern = types.StringValue(value.String())
	} else {
		data.Pattern = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host"); value.Exists() && !data.Hosts.IsNull() {
		data.Hosts = helpers.GetStringListXML(value.Array())
	} else {
		data.Hosts = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-id"); value.Exists() && !data.UserId.IsNull() {
		data.UserId = types.StringValue(value.String())
	} else {
		data.UserId = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/context"); value.Exists() && !data.PhoneContext.IsNull() {
		data.PhoneContext = types.StringValue(value.String())
	} else {
		data.PhoneContext = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/number"); value.Exists() && !data.PhoneNumber.IsNull() {
		data.PhoneNumber = types.StringValue(value.String())
	} else {
		data.PhoneNumber = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassURI) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() {
		data.Type = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pattern"); value.Exists() {
		data.Pattern = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host"); value.Exists() {
		data.Hosts = helpers.GetStringListXML(value.Array())
	} else {
		data.Hosts = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-id"); value.Exists() {
		data.UserId = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/context"); value.Exists() {
		data.PhoneContext = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/number"); value.Exists() {
		data.PhoneNumber = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassURIData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() {
		data.Type = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/pattern"); value.Exists() {
		data.Pattern = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host"); value.Exists() {
		data.Hosts = helpers.GetStringListXML(value.Array())
	} else {
		data.Hosts = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-id"); value.Exists() {
		data.UserId = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/context"); value.Exists() {
		data.PhoneContext = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/phone/number"); value.Exists() {
		data.PhoneNumber = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassURI) addDeletedItemsXML(ctx context.Context, state VoiceClassURI, body string) string {
	b := netconf.NewBody(body)
	if !state.PhoneNumber.IsNull() && data.PhoneNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/phone/number")
	}
	if !state.PhoneContext.IsNull() && data.PhoneContext.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/phone/context")
	}
	if !state.UserId.IsNull() && data.UserId.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-id")
	}
	if !state.Hosts.IsNull() {
		if data.Hosts.IsNull() {
			var values []string
			state.Hosts.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/host[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.Hosts.ElementsAs(ctx, &dataValues, false)
			state.Hosts.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/host[.=%v]", v))
				}
			}
		}
	}
	if !state.Pattern.IsNull() && data.Pattern.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/pattern")
	}
	if !state.Type.IsNull() && data.Type.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/type")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassURI) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.PhoneNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/phone/number")
	}
	if !data.PhoneContext.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/phone/context")
	}
	if !data.UserId.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-id")
	}
	if !data.Hosts.IsNull() {
		var values []string
		data.Hosts.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/host[.=%v]", v))
		}
	}
	if !data.Pattern.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/pattern")
	}
	if !data.Type.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/type")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
