// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceTranslationProfile struct {
	Device           types.String `tfsdk:"device"`
	Id               types.String `tfsdk:"id"`
	DeleteMode       types.String `tfsdk:"delete_mode"`
	Tag              types.String `tfsdk:"tag"`
	TranslateCalled  types.String `tfsdk:"translate_called"`
	TranslateCalling types.String `tfsdk:"translate_calling"`
}

type VoiceTranslationProfileData struct {
	Device           types.String `tfsdk:"device"`
	Id               types.String `tfsdk:"id"`
	Tag              types.String `tfsdk:"tag"`
	TranslateCalled  types.String `tfsdk:"translate_called"`
	TranslateCalling types.String `tfsdk:"translate_calling"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceTranslationProfile) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-profile=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueString())))
}

func (data VoiceTranslationProfileData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-profile=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceTranslationProfile) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-profile[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueString()))
	return path
}

func (data VoiceTranslationProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-profile[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceTranslationProfile) toBodyXML(ctx context.Context, config VoiceTranslationProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceTranslationProfile) addToBodyXML(ctx context.Context, config VoiceTranslationProfile, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", data.Tag.ValueString())
	}
	if !data.TranslateCalled.IsNull() && !data.TranslateCalled.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/translate/called", data.TranslateCalled.ValueString())
	}
	if !data.TranslateCalling.IsNull() && !data.TranslateCalling.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/translate/calling", data.TranslateCalling.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceTranslationProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.StringValue(value.String())
	} else {
		data.Tag = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/called"); value.Exists() && !data.TranslateCalled.IsNull() {
		data.TranslateCalled = types.StringValue(value.String())
	} else {
		data.TranslateCalled = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/calling"); value.Exists() && !data.TranslateCalling.IsNull() {
		data.TranslateCalling = types.StringValue(value.String())
	} else {
		data.TranslateCalling = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceTranslationProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/called"); value.Exists() {
		data.TranslateCalled = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/calling"); value.Exists() {
		data.TranslateCalling = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceTranslationProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/called"); value.Exists() {
		data.TranslateCalled = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translate/calling"); value.Exists() {
		data.TranslateCalling = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceTranslationProfile) addDeletedItemsXML(ctx context.Context, state VoiceTranslationProfile, body string) string {
	b := netconf.NewBody(body)
	if !state.TranslateCalling.IsNull() && data.TranslateCalling.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/translate/calling")
	}
	if !state.TranslateCalled.IsNull() && data.TranslateCalled.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/translate/called")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceTranslationProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.TranslateCalling.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/translate/calling")
	}
	if !data.TranslateCalled.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/translate/called")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
