// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassSIPProfiles struct {
	Device      types.String                 `tfsdk:"device"`
	Id          types.String                 `tfsdk:"id"`
	DeleteMode  types.String                 `tfsdk:"delete_mode"`
	Tag         types.Int64                  `tfsdk:"tag"`
	Description types.String                 `tfsdk:"description"`
	Rules       []VoiceClassSIPProfilesRules `tfsdk:"rules"`
}
type VoiceClassSIPProfilesRules struct {
	Rule                                   types.Int64  `tfsdk:"rule"`
	RequestMethod                          types.String `tfsdk:"request_method"`
	RequestSipHeader                       types.String `tfsdk:"request_sip_header"`
	RequestSipHeaderModifyPattern          types.String `tfsdk:"request_sip_header_modify_pattern"`
	RequestSipHeaderModifyReplace          types.String `tfsdk:"request_sip_header_modify_replace"`
	ResponseCode                           types.String `tfsdk:"response_code"`
	ResponseSipHeader                      types.String `tfsdk:"response_sip_header"`
	ResponseSipHeaderModifyPattern         types.String `tfsdk:"response_sip_header_modify_pattern"`
	ResponseSipHeaderModifyReplace         types.String `tfsdk:"response_sip_header_modify_replace"`
	RequestSipHeaderAdd                    types.String `tfsdk:"request_sip_header_add"`
	RequestSipHeaderRemove                 types.Bool   `tfsdk:"request_sip_header_remove"`
	RequestSdpHeader                       types.String `tfsdk:"request_sdp_header"`
	RequestSdpHeaderModifyPattern          types.String `tfsdk:"request_sdp_header_modify_pattern"`
	RequestSdpHeaderModifyReplace          types.String `tfsdk:"request_sdp_header_modify_replace"`
	ResponseSdpHeader                      types.String `tfsdk:"response_sdp_header"`
	ResponseSdpHeaderModifyPattern         types.String `tfsdk:"response_sdp_header_modify_pattern"`
	ResponseSdpHeaderModifyReplace         types.String `tfsdk:"response_sdp_header_modify_replace"`
	RequestSdpHeaderAdd                    types.String `tfsdk:"request_sdp_header_add"`
	RequestSdpHeaderRemove                 types.Bool   `tfsdk:"request_sdp_header_remove"`
	RequestPeerHeaderSip                   types.String `tfsdk:"request_peer_header_sip"`
	RequestPeerHeaderSipCopyPattern        types.String `tfsdk:"request_peer_header_sip_copy_pattern"`
	RequestPeerHeaderSipCopyVariable       types.String `tfsdk:"request_peer_header_sip_copy_variable"`
	RequestPeerHeaderSipRequriCopyPattern  types.String `tfsdk:"request_peer_header_sip_requri_copy_pattern"`
	RequestPeerHeaderSipRequriCopyVariable types.String `tfsdk:"request_peer_header_sip_requri_copy_variable"`
}

type VoiceClassSIPProfilesData struct {
	Device      types.String                     `tfsdk:"device"`
	Id          types.String                     `tfsdk:"id"`
	Tag         types.Int64                      `tfsdk:"tag"`
	Description types.String                     `tfsdk:"description"`
	Rules       []VoiceClassSIPProfilesRulesData `tfsdk:"rules"`
}
type VoiceClassSIPProfilesRulesData struct {
	Rule                                   types.Int64  `tfsdk:"rule"`
	RequestMethod                          types.String `tfsdk:"request_method"`
	RequestSipHeader                       types.String `tfsdk:"request_sip_header"`
	RequestSipHeaderModifyPattern          types.String `tfsdk:"request_sip_header_modify_pattern"`
	RequestSipHeaderModifyReplace          types.String `tfsdk:"request_sip_header_modify_replace"`
	ResponseCode                           types.String `tfsdk:"response_code"`
	ResponseSipHeader                      types.String `tfsdk:"response_sip_header"`
	ResponseSipHeaderModifyPattern         types.String `tfsdk:"response_sip_header_modify_pattern"`
	ResponseSipHeaderModifyReplace         types.String `tfsdk:"response_sip_header_modify_replace"`
	RequestSipHeaderAdd                    types.String `tfsdk:"request_sip_header_add"`
	RequestSipHeaderRemove                 types.Bool   `tfsdk:"request_sip_header_remove"`
	RequestSdpHeader                       types.String `tfsdk:"request_sdp_header"`
	RequestSdpHeaderModifyPattern          types.String `tfsdk:"request_sdp_header_modify_pattern"`
	RequestSdpHeaderModifyReplace          types.String `tfsdk:"request_sdp_header_modify_replace"`
	ResponseSdpHeader                      types.String `tfsdk:"response_sdp_header"`
	ResponseSdpHeaderModifyPattern         types.String `tfsdk:"response_sdp_header_modify_pattern"`
	ResponseSdpHeaderModifyReplace         types.String `tfsdk:"response_sdp_header_modify_replace"`
	RequestSdpHeaderAdd                    types.String `tfsdk:"request_sdp_header_add"`
	RequestSdpHeaderRemove                 types.Bool   `tfsdk:"request_sdp_header_remove"`
	RequestPeerHeaderSip                   types.String `tfsdk:"request_peer_header_sip"`
	RequestPeerHeaderSipCopyPattern        types.String `tfsdk:"request_peer_header_sip_copy_pattern"`
	RequestPeerHeaderSipCopyVariable       types.String `tfsdk:"request_peer_header_sip_copy_variable"`
	RequestPeerHeaderSipRequriCopyPattern  types.String `tfsdk:"request_peer_header_sip_requri_copy_pattern"`
	RequestPeerHeaderSipRequriCopyVariable types.String `tfsdk:"request_peer_header_sip_requri_copy_variable"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassSIPProfiles) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-profiles=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassSIPProfilesData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-profiles=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassSIPProfiles) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-profiles[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassSIPProfilesData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-profiles[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassSIPProfiles) toBodyXML(ctx context.Context, config VoiceClassSIPProfiles) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassSIPProfiles) addToBodyXML(ctx context.Context, config VoiceClassSIPProfiles, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if len(data.Rules) > 0 {
		for _, item := range data.Rules {
			cBody := netconf.Body{}
			if !item.Rule.IsNull() && !item.Rule.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "id", strconv.FormatInt(item.Rule.ValueInt64(), 10))
			}
			if !item.RequestMethod.IsNull() && !item.RequestMethod.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-requests", item.RequestMethod.ValueString())
			}
			if !item.RequestSipHeader.IsNull() && !item.RequestSipHeader.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-header/header", item.RequestSipHeader.ValueString())
			}
			if !item.RequestSipHeaderModifyPattern.IsNull() && !item.RequestSipHeaderModifyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-header/MODIFY/pattern", item.RequestSipHeaderModifyPattern.ValueString())
			}
			if !item.RequestSipHeaderModifyReplace.IsNull() && !item.RequestSipHeaderModifyReplace.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-header/MODIFY/replace-pattern", item.RequestSipHeaderModifyReplace.ValueString())
			}
			if !item.ResponseCode.IsNull() && !item.ResponseCode.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sip-responses", item.ResponseCode.ValueString())
			}
			if !item.ResponseSipHeader.IsNull() && !item.ResponseSipHeader.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sip-header/header", item.ResponseSipHeader.ValueString())
			}
			if !item.ResponseSipHeaderModifyPattern.IsNull() && !item.ResponseSipHeaderModifyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sip-header/MODIFY/pattern", item.ResponseSipHeaderModifyPattern.ValueString())
			}
			if !item.ResponseSipHeaderModifyReplace.IsNull() && !item.ResponseSipHeaderModifyReplace.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sip-header/MODIFY/replace-pattern", item.ResponseSipHeaderModifyReplace.ValueString())
			}
			if !item.RequestSipHeaderAdd.IsNull() && !item.RequestSipHeaderAdd.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-header/ADD", item.RequestSipHeaderAdd.ValueString())
			}
			if !item.RequestSipHeaderRemove.IsNull() && !item.RequestSipHeaderRemove.IsUnknown() {
				if item.RequestSipHeaderRemove.ValueBool() {
					cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sip-header/REMOVE", "")
				} else {
					cBody = helpers.RemoveFromXPath(cBody, "rule-response-request/request/sip-header/REMOVE")
				}
			}
			if !item.RequestSdpHeader.IsNull() && !item.RequestSdpHeader.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sdp-header/header", item.RequestSdpHeader.ValueString())
			}
			if !item.RequestSdpHeaderModifyPattern.IsNull() && !item.RequestSdpHeaderModifyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sdp-header/MODIFY/pattern", item.RequestSdpHeaderModifyPattern.ValueString())
			}
			if !item.RequestSdpHeaderModifyReplace.IsNull() && !item.RequestSdpHeaderModifyReplace.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sdp-header/MODIFY/replace-pattern", item.RequestSdpHeaderModifyReplace.ValueString())
			}
			if !item.ResponseSdpHeader.IsNull() && !item.ResponseSdpHeader.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sdp-header/header", item.ResponseSdpHeader.ValueString())
			}
			if !item.ResponseSdpHeaderModifyPattern.IsNull() && !item.ResponseSdpHeaderModifyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sdp-header/MODIFY/pattern", item.ResponseSdpHeaderModifyPattern.ValueString())
			}
			if !item.ResponseSdpHeaderModifyReplace.IsNull() && !item.ResponseSdpHeaderModifyReplace.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/response/sdp-header/MODIFY/replace-pattern", item.ResponseSdpHeaderModifyReplace.ValueString())
			}
			if !item.RequestSdpHeaderAdd.IsNull() && !item.RequestSdpHeaderAdd.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sdp-header/ADD", item.RequestSdpHeaderAdd.ValueString())
			}
			if !item.RequestSdpHeaderRemove.IsNull() && !item.RequestSdpHeaderRemove.IsUnknown() {
				if item.RequestSdpHeaderRemove.ValueBool() {
					cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/sdp-header/REMOVE", "")
				} else {
					cBody = helpers.RemoveFromXPath(cBody, "rule-response-request/request/sdp-header/REMOVE")
				}
			}
			if !item.RequestPeerHeaderSip.IsNull() && !item.RequestPeerHeaderSip.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/peer-header/sip/header-name-copy/header", item.RequestPeerHeaderSip.ValueString())
			}
			if !item.RequestPeerHeaderSipCopyPattern.IsNull() && !item.RequestPeerHeaderSipCopyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/pattern", item.RequestPeerHeaderSipCopyPattern.ValueString())
			}
			if !item.RequestPeerHeaderSipCopyVariable.IsNull() && !item.RequestPeerHeaderSipCopyVariable.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/variable", item.RequestPeerHeaderSipCopyVariable.ValueString())
			}
			if !item.RequestPeerHeaderSipRequriCopyPattern.IsNull() && !item.RequestPeerHeaderSipRequriCopyPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/pattern", item.RequestPeerHeaderSipRequriCopyPattern.ValueString())
			}
			if !item.RequestPeerHeaderSipRequriCopyVariable.IsNull() && !item.RequestPeerHeaderSipRequriCopyVariable.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/variable", item.RequestPeerHeaderSipRequriCopyVariable.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/rule", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassSIPProfiles) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	for i := range data.Rules {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.Rules[i].Rule.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "id"); value.Exists() && !data.Rules[i].Rule.IsNull() {
			data.Rules[i].Rule = types.Int64Value(value.Int())
		} else {
			data.Rules[i].Rule = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-requests"); value.Exists() && !data.Rules[i].RequestMethod.IsNull() {
			data.Rules[i].RequestMethod = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestMethod = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-header/header"); value.Exists() && !data.Rules[i].RequestSipHeader.IsNull() {
			data.Rules[i].RequestSipHeader = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSipHeader = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-header/MODIFY/pattern"); value.Exists() && !data.Rules[i].RequestSipHeaderModifyPattern.IsNull() {
			data.Rules[i].RequestSipHeaderModifyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSipHeaderModifyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-header/MODIFY/replace-pattern"); value.Exists() && !data.Rules[i].RequestSipHeaderModifyReplace.IsNull() {
			data.Rules[i].RequestSipHeaderModifyReplace = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSipHeaderModifyReplace = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sip-responses"); value.Exists() && !data.Rules[i].ResponseCode.IsNull() {
			data.Rules[i].ResponseCode = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseCode = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sip-header/header"); value.Exists() && !data.Rules[i].ResponseSipHeader.IsNull() {
			data.Rules[i].ResponseSipHeader = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSipHeader = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sip-header/MODIFY/pattern"); value.Exists() && !data.Rules[i].ResponseSipHeaderModifyPattern.IsNull() {
			data.Rules[i].ResponseSipHeaderModifyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSipHeaderModifyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sip-header/MODIFY/replace-pattern"); value.Exists() && !data.Rules[i].ResponseSipHeaderModifyReplace.IsNull() {
			data.Rules[i].ResponseSipHeaderModifyReplace = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSipHeaderModifyReplace = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-header/ADD"); value.Exists() && !data.Rules[i].RequestSipHeaderAdd.IsNull() {
			data.Rules[i].RequestSipHeaderAdd = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSipHeaderAdd = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sip-header/REMOVE"); !data.Rules[i].RequestSipHeaderRemove.IsNull() {
			if value.Exists() {
				data.Rules[i].RequestSipHeaderRemove = types.BoolValue(true)
			} else {
				data.Rules[i].RequestSipHeaderRemove = types.BoolValue(false)
			}
		} else {
			data.Rules[i].RequestSipHeaderRemove = types.BoolNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sdp-header/header"); value.Exists() && !data.Rules[i].RequestSdpHeader.IsNull() {
			data.Rules[i].RequestSdpHeader = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSdpHeader = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sdp-header/MODIFY/pattern"); value.Exists() && !data.Rules[i].RequestSdpHeaderModifyPattern.IsNull() {
			data.Rules[i].RequestSdpHeaderModifyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSdpHeaderModifyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sdp-header/MODIFY/replace-pattern"); value.Exists() && !data.Rules[i].RequestSdpHeaderModifyReplace.IsNull() {
			data.Rules[i].RequestSdpHeaderModifyReplace = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSdpHeaderModifyReplace = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sdp-header/header"); value.Exists() && !data.Rules[i].ResponseSdpHeader.IsNull() {
			data.Rules[i].ResponseSdpHeader = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSdpHeader = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sdp-header/MODIFY/pattern"); value.Exists() && !data.Rules[i].ResponseSdpHeaderModifyPattern.IsNull() {
			data.Rules[i].ResponseSdpHeaderModifyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSdpHeaderModifyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/response/sdp-header/MODIFY/replace-pattern"); value.Exists() && !data.Rules[i].ResponseSdpHeaderModifyReplace.IsNull() {
			data.Rules[i].ResponseSdpHeaderModifyReplace = types.StringValue(value.String())
		} else {
			data.Rules[i].ResponseSdpHeaderModifyReplace = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sdp-header/ADD"); value.Exists() && !data.Rules[i].RequestSdpHeaderAdd.IsNull() {
			data.Rules[i].RequestSdpHeaderAdd = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestSdpHeaderAdd = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/sdp-header/REMOVE"); !data.Rules[i].RequestSdpHeaderRemove.IsNull() {
			if value.Exists() {
				data.Rules[i].RequestSdpHeaderRemove = types.BoolValue(true)
			} else {
				data.Rules[i].RequestSdpHeaderRemove = types.BoolValue(false)
			}
		} else {
			data.Rules[i].RequestSdpHeaderRemove = types.BoolNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/peer-header/sip/header-name-copy/header"); value.Exists() && !data.Rules[i].RequestPeerHeaderSip.IsNull() {
			data.Rules[i].RequestPeerHeaderSip = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestPeerHeaderSip = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/pattern"); value.Exists() && !data.Rules[i].RequestPeerHeaderSipCopyPattern.IsNull() {
			data.Rules[i].RequestPeerHeaderSipCopyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestPeerHeaderSipCopyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/variable"); value.Exists() && !data.Rules[i].RequestPeerHeaderSipCopyVariable.IsNull() {
			data.Rules[i].RequestPeerHeaderSipCopyVariable = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestPeerHeaderSipCopyVariable = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/pattern"); value.Exists() && !data.Rules[i].RequestPeerHeaderSipRequriCopyPattern.IsNull() {
			data.Rules[i].RequestPeerHeaderSipRequriCopyPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestPeerHeaderSipRequriCopyPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/variable"); value.Exists() && !data.Rules[i].RequestPeerHeaderSipRequriCopyVariable.IsNull() {
			data.Rules[i].RequestPeerHeaderSipRequriCopyVariable = types.StringValue(value.String())
		} else {
			data.Rules[i].RequestPeerHeaderSipRequriCopyVariable = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassSIPProfiles) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule"); value.Exists() {
		data.Rules = make([]VoiceClassSIPProfilesRules, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassSIPProfilesRules{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.Rule = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-requests"); cValue.Exists() {
				item.RequestMethod = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/header"); cValue.Exists() {
				item.RequestSipHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/MODIFY/pattern"); cValue.Exists() {
				item.RequestSipHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.RequestSipHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-responses"); cValue.Exists() {
				item.ResponseCode = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/header"); cValue.Exists() {
				item.ResponseSipHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/MODIFY/pattern"); cValue.Exists() {
				item.ResponseSipHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.ResponseSipHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/ADD"); cValue.Exists() {
				item.RequestSipHeaderAdd = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/REMOVE"); cValue.Exists() {
				item.RequestSipHeaderRemove = types.BoolValue(true)
			} else {
				item.RequestSipHeaderRemove = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/header"); cValue.Exists() {
				item.RequestSdpHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/MODIFY/pattern"); cValue.Exists() {
				item.RequestSdpHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.RequestSdpHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/header"); cValue.Exists() {
				item.ResponseSdpHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/MODIFY/pattern"); cValue.Exists() {
				item.ResponseSdpHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.ResponseSdpHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/ADD"); cValue.Exists() {
				item.RequestSdpHeaderAdd = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/REMOVE"); cValue.Exists() {
				item.RequestSdpHeaderRemove = types.BoolValue(true)
			} else {
				item.RequestSdpHeaderRemove = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/header"); cValue.Exists() {
				item.RequestPeerHeaderSip = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/pattern"); cValue.Exists() {
				item.RequestPeerHeaderSipCopyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/variable"); cValue.Exists() {
				item.RequestPeerHeaderSipCopyVariable = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/pattern"); cValue.Exists() {
				item.RequestPeerHeaderSipRequriCopyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/variable"); cValue.Exists() {
				item.RequestPeerHeaderSipRequriCopyVariable = types.StringValue(cValue.String())
			}
			data.Rules = append(data.Rules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassSIPProfilesData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule"); value.Exists() {
		data.Rules = make([]VoiceClassSIPProfilesRulesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassSIPProfilesRulesData{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.Rule = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-requests"); cValue.Exists() {
				item.RequestMethod = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/header"); cValue.Exists() {
				item.RequestSipHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/MODIFY/pattern"); cValue.Exists() {
				item.RequestSipHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.RequestSipHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-responses"); cValue.Exists() {
				item.ResponseCode = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/header"); cValue.Exists() {
				item.ResponseSipHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/MODIFY/pattern"); cValue.Exists() {
				item.ResponseSipHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sip-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.ResponseSipHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/ADD"); cValue.Exists() {
				item.RequestSipHeaderAdd = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sip-header/REMOVE"); cValue.Exists() {
				item.RequestSipHeaderRemove = types.BoolValue(true)
			} else {
				item.RequestSipHeaderRemove = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/header"); cValue.Exists() {
				item.RequestSdpHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/MODIFY/pattern"); cValue.Exists() {
				item.RequestSdpHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.RequestSdpHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/header"); cValue.Exists() {
				item.ResponseSdpHeader = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/MODIFY/pattern"); cValue.Exists() {
				item.ResponseSdpHeaderModifyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/response/sdp-header/MODIFY/replace-pattern"); cValue.Exists() {
				item.ResponseSdpHeaderModifyReplace = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/ADD"); cValue.Exists() {
				item.RequestSdpHeaderAdd = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/sdp-header/REMOVE"); cValue.Exists() {
				item.RequestSdpHeaderRemove = types.BoolValue(true)
			} else {
				item.RequestSdpHeaderRemove = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/header"); cValue.Exists() {
				item.RequestPeerHeaderSip = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/pattern"); cValue.Exists() {
				item.RequestPeerHeaderSipCopyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/header-name-copy/COPY/variable"); cValue.Exists() {
				item.RequestPeerHeaderSipCopyVariable = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/pattern"); cValue.Exists() {
				item.RequestPeerHeaderSipRequriCopyPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/variable"); cValue.Exists() {
				item.RequestPeerHeaderSipRequriCopyVariable = types.StringValue(cValue.String())
			}
			data.Rules = append(data.Rules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassSIPProfiles) addDeletedItemsXML(ctx context.Context, state VoiceClassSIPProfiles, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Rules {
		stateKeys := [...]string{"id"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Rules[i].Rule.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Rules[i].Rule.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Rules {
			found = true
			if state.Rules[i].Rule.ValueInt64() != data.Rules[j].Rule.ValueInt64() {
				found = false
			}
			if found {
				if !state.Rules[i].RequestPeerHeaderSipRequriCopyVariable.IsNull() && data.Rules[j].RequestPeerHeaderSipRequriCopyVariable.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/variable", predicates))
				}
				if !state.Rules[i].RequestPeerHeaderSipRequriCopyPattern.IsNull() && data.Rules[j].RequestPeerHeaderSipRequriCopyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/peer-header/sip/SIP-Req-URI/COPY/pattern", predicates))
				}
				if !state.Rules[i].RequestPeerHeaderSipCopyVariable.IsNull() && data.Rules[j].RequestPeerHeaderSipCopyVariable.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/peer-header/sip/header-name-copy/COPY/variable", predicates))
				}
				if !state.Rules[i].RequestPeerHeaderSipCopyPattern.IsNull() && data.Rules[j].RequestPeerHeaderSipCopyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/peer-header/sip/header-name-copy/COPY/pattern", predicates))
				}
				if !state.Rules[i].RequestPeerHeaderSip.IsNull() && data.Rules[j].RequestPeerHeaderSip.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/peer-header/sip/header-name-copy/header", predicates))
				}
				if !state.Rules[i].RequestSdpHeaderRemove.IsNull() && data.Rules[j].RequestSdpHeaderRemove.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sdp-header/REMOVE", predicates))
				}
				if !state.Rules[i].RequestSdpHeaderAdd.IsNull() && data.Rules[j].RequestSdpHeaderAdd.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sdp-header/ADD", predicates))
				}
				if !state.Rules[i].ResponseSdpHeaderModifyReplace.IsNull() && data.Rules[j].ResponseSdpHeaderModifyReplace.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sdp-header/MODIFY/replace-pattern", predicates))
				}
				if !state.Rules[i].ResponseSdpHeaderModifyPattern.IsNull() && data.Rules[j].ResponseSdpHeaderModifyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sdp-header/MODIFY/pattern", predicates))
				}
				if !state.Rules[i].ResponseSdpHeader.IsNull() && data.Rules[j].ResponseSdpHeader.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sdp-header/header", predicates))
				}
				if !state.Rules[i].RequestSdpHeaderModifyReplace.IsNull() && data.Rules[j].RequestSdpHeaderModifyReplace.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sdp-header/MODIFY/replace-pattern", predicates))
				}
				if !state.Rules[i].RequestSdpHeaderModifyPattern.IsNull() && data.Rules[j].RequestSdpHeaderModifyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sdp-header/MODIFY/pattern", predicates))
				}
				if !state.Rules[i].RequestSdpHeader.IsNull() && data.Rules[j].RequestSdpHeader.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sdp-header/header", predicates))
				}
				if !state.Rules[i].RequestSipHeaderRemove.IsNull() && data.Rules[j].RequestSipHeaderRemove.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-header/REMOVE", predicates))
				}
				if !state.Rules[i].RequestSipHeaderAdd.IsNull() && data.Rules[j].RequestSipHeaderAdd.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-header/ADD", predicates))
				}
				if !state.Rules[i].ResponseSipHeaderModifyReplace.IsNull() && data.Rules[j].ResponseSipHeaderModifyReplace.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sip-header/MODIFY/replace-pattern", predicates))
				}
				if !state.Rules[i].ResponseSipHeaderModifyPattern.IsNull() && data.Rules[j].ResponseSipHeaderModifyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sip-header/MODIFY/pattern", predicates))
				}
				if !state.Rules[i].ResponseSipHeader.IsNull() && data.Rules[j].ResponseSipHeader.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sip-header/header", predicates))
				}
				if !state.Rules[i].ResponseCode.IsNull() && data.Rules[j].ResponseCode.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/response/sip-responses", predicates))
				}
				if !state.Rules[i].RequestSipHeaderModifyReplace.IsNull() && data.Rules[j].RequestSipHeaderModifyReplace.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-header/MODIFY/replace-pattern", predicates))
				}
				if !state.Rules[i].RequestSipHeaderModifyPattern.IsNull() && data.Rules[j].RequestSipHeaderModifyPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-header/MODIFY/pattern", predicates))
				}
				if !state.Rules[i].RequestSipHeader.IsNull() && data.Rules[j].RequestSipHeader.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-header/header", predicates))
				}
				if !state.Rules[i].RequestMethod.IsNull() && data.Rules[j].RequestMethod.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/rule-response-request/request/sip-requests", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v", predicates))
		}
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassSIPProfiles) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Rules {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.Rules[i].Rule.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/rule%v", predicates))
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
