// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceTrunkGroup struct {
	Device                     types.String `tfsdk:"device"`
	Id                         types.String `tfsdk:"id"`
	DeleteMode                 types.String `tfsdk:"delete_mode"`
	Name                       types.String `tfsdk:"name"`
	HuntSchemeMethod           types.String `tfsdk:"hunt_scheme_method"`
	MaxRetry                   types.Int64  `tfsdk:"max_retry"`
	TranslationProfileIncoming types.String `tfsdk:"translation_profile_incoming"`
	TranslationProfileOutgoing types.String `tfsdk:"translation_profile_outgoing"`
}

type VoiceTrunkGroupData struct {
	Device                     types.String `tfsdk:"device"`
	Id                         types.String `tfsdk:"id"`
	Name                       types.String `tfsdk:"name"`
	HuntSchemeMethod           types.String `tfsdk:"hunt_scheme_method"`
	MaxRetry                   types.Int64  `tfsdk:"max_retry"`
	TranslationProfileIncoming types.String `tfsdk:"translation_profile_incoming"`
	TranslationProfileOutgoing types.String `tfsdk:"translation_profile_outgoing"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceTrunkGroup) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:trunk/group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

func (data VoiceTrunkGroupData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:trunk/group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceTrunkGroup) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:trunk/group[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

func (data VoiceTrunkGroupData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:trunk/group[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceTrunkGroup) toBodyXML(ctx context.Context, config VoiceTrunkGroup) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceTrunkGroup) addToBodyXML(ctx context.Context, config VoiceTrunkGroup, body netconf.Body) netconf.Body {
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", data.Name.ValueString())
	}
	if !data.HuntSchemeMethod.IsNull() && !data.HuntSchemeMethod.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/hunt-scheme/hunt-method", data.HuntSchemeMethod.ValueString())
	}
	if !data.MaxRetry.IsNull() && !data.MaxRetry.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/max-retry", strconv.FormatInt(data.MaxRetry.ValueInt64(), 10))
	}
	if !data.TranslationProfileIncoming.IsNull() && !data.TranslationProfileIncoming.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/translation-profile/incoming", data.TranslationProfileIncoming.ValueString())
	}
	if !data.TranslationProfileOutgoing.IsNull() && !data.TranslationProfileOutgoing.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/translation-profile/outgoing", data.TranslationProfileOutgoing.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceTrunkGroup) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/hunt-method"); value.Exists() && !data.HuntSchemeMethod.IsNull() {
		data.HuntSchemeMethod = types.StringValue(value.String())
	} else {
		data.HuntSchemeMethod = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/max-retry"); value.Exists() && !data.MaxRetry.IsNull() {
		data.MaxRetry = types.Int64Value(value.Int())
	} else {
		data.MaxRetry = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/incoming"); value.Exists() && !data.TranslationProfileIncoming.IsNull() {
		data.TranslationProfileIncoming = types.StringValue(value.String())
	} else {
		data.TranslationProfileIncoming = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/outgoing"); value.Exists() && !data.TranslationProfileOutgoing.IsNull() {
		data.TranslationProfileOutgoing = types.StringValue(value.String())
	} else {
		data.TranslationProfileOutgoing = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceTrunkGroup) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/hunt-method"); value.Exists() {
		data.HuntSchemeMethod = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/max-retry"); value.Exists() {
		data.MaxRetry = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/incoming"); value.Exists() {
		data.TranslationProfileIncoming = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/outgoing"); value.Exists() {
		data.TranslationProfileOutgoing = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceTrunkGroupData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/hunt-method"); value.Exists() {
		data.HuntSchemeMethod = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/max-retry"); value.Exists() {
		data.MaxRetry = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/incoming"); value.Exists() {
		data.TranslationProfileIncoming = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/translation-profile/outgoing"); value.Exists() {
		data.TranslationProfileOutgoing = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceTrunkGroup) addDeletedItemsXML(ctx context.Context, state VoiceTrunkGroup, body string) string {
	b := netconf.NewBody(body)
	if !state.TranslationProfileOutgoing.IsNull() && data.TranslationProfileOutgoing.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/translation-profile/outgoing")
	}
	if !state.TranslationProfileIncoming.IsNull() && data.TranslationProfileIncoming.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/translation-profile/incoming")
	}
	if !state.MaxRetry.IsNull() && data.MaxRetry.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/max-retry")
	}
	if !state.HuntSchemeMethod.IsNull() && data.HuntSchemeMethod.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/hunt-scheme/hunt-method")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceTrunkGroup) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.TranslationProfileOutgoing.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/translation-profile/outgoing")
	}
	if !data.TranslationProfileIncoming.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/translation-profile/incoming")
	}
	if !data.MaxRetry.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/max-retry")
	}
	if !data.HuntSchemeMethod.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/hunt-scheme/hunt-method")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
