// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceCard struct {
	Device             types.String `tfsdk:"device"`
	Id                 types.String `tfsdk:"id"`
	DeleteMode         types.String `tfsdk:"delete_mode"`
	Location           types.String `tfsdk:"location"`
	LocalBypass        types.Bool   `tfsdk:"local_bypass"`
	DspServicesDspfarm types.Bool   `tfsdk:"dsp_services_dspfarm"`
}

type VoiceCardData struct {
	Device             types.String `tfsdk:"device"`
	Id                 types.String `tfsdk:"id"`
	Location           types.String `tfsdk:"location"`
	LocalBypass        types.Bool   `tfsdk:"local_bypass"`
	DspServicesDspfarm types.Bool   `tfsdk:"dsp_services_dspfarm"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceCard) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice-card-sb=%v", url.QueryEscape(fmt.Sprintf("%v", data.Location.ValueString())))
}

func (data VoiceCardData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice-card-sb=%v", url.QueryEscape(fmt.Sprintf("%v", data.Location.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceCard) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice-card-sb[sb=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Location.ValueString()))
	return path
}

func (data VoiceCardData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice-card-sb[sb=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Location.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceCard) toBodyXML(ctx context.Context, config VoiceCard) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceCard) addToBodyXML(ctx context.Context, config VoiceCard, body netconf.Body) netconf.Body {
	if !data.Location.IsNull() && !data.Location.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/sb", data.Location.ValueString())
	}
	if !data.LocalBypass.IsNull() && !data.LocalBypass.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/local-bypass", data.LocalBypass.ValueBool())
	}
	if !data.DspServicesDspfarm.IsNull() && !data.DspServicesDspfarm.IsUnknown() {
		if data.DspServicesDspfarm.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/dsp/services/dspfarm", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/dsp/services/dspfarm")
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceCard) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sb"); value.Exists() && !data.Location.IsNull() {
		data.Location = types.StringValue(value.String())
	} else {
		data.Location = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/local-bypass"); !data.LocalBypass.IsNull() {
		if value.Exists() {
			data.LocalBypass = types.BoolValue(value.Bool())
		}
	} else {
		data.LocalBypass = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dsp/services/dspfarm"); !data.DspServicesDspfarm.IsNull() {
		if value.Exists() {
			data.DspServicesDspfarm = types.BoolValue(true)
		} else {
			data.DspServicesDspfarm = types.BoolValue(false)
		}
	} else {
		data.DspServicesDspfarm = types.BoolNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceCard) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/local-bypass"); value.Exists() {
		data.LocalBypass = types.BoolValue(value.Bool())
	} else {
		data.LocalBypass = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dsp/services/dspfarm"); value.Exists() {
		data.DspServicesDspfarm = types.BoolValue(true)
	} else {
		data.DspServicesDspfarm = types.BoolValue(false)
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceCardData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/local-bypass"); value.Exists() {
		data.LocalBypass = types.BoolValue(value.Bool())
	} else {
		data.LocalBypass = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dsp/services/dspfarm"); value.Exists() {
		data.DspServicesDspfarm = types.BoolValue(true)
	} else {
		data.DspServicesDspfarm = types.BoolValue(false)
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceCard) addDeletedItemsXML(ctx context.Context, state VoiceCard, body string) string {
	b := netconf.NewBody(body)
	if !state.DspServicesDspfarm.IsNull() && data.DspServicesDspfarm.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/dsp/services/dspfarm")
	}
	if !state.LocalBypass.IsNull() && data.LocalBypass.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/local-bypass")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceCard) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.DspServicesDspfarm.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/dsp/services/dspfarm")
	}
	if !data.LocalBypass.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/local-bypass")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
