// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceTranslationRule struct {
	Device     types.String                `tfsdk:"device"`
	Id         types.String                `tfsdk:"id"`
	DeleteMode types.String                `tfsdk:"delete_mode"`
	Tag        types.Int64                 `tfsdk:"tag"`
	Rules      []VoiceTranslationRuleRules `tfsdk:"rules"`
}
type VoiceTranslationRuleRules struct {
	RuleId                     types.Int64  `tfsdk:"rule_id"`
	MatchingReplacementPattern types.String `tfsdk:"matching_replacement_pattern"`
	Reject                     types.String `tfsdk:"reject"`
}

type VoiceTranslationRuleData struct {
	Device types.String                    `tfsdk:"device"`
	Id     types.String                    `tfsdk:"id"`
	Tag    types.Int64                     `tfsdk:"tag"`
	Rules  []VoiceTranslationRuleRulesData `tfsdk:"rules"`
}
type VoiceTranslationRuleRulesData struct {
	RuleId                     types.Int64  `tfsdk:"rule_id"`
	MatchingReplacementPattern types.String `tfsdk:"matching_replacement_pattern"`
	Reject                     types.String `tfsdk:"reject"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceTranslationRule) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-rule=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceTranslationRuleData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-rule=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceTranslationRule) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-rule[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceTranslationRuleData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/translation-rule[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceTranslationRule) toBodyXML(ctx context.Context, config VoiceTranslationRule) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceTranslationRule) addToBodyXML(ctx context.Context, config VoiceTranslationRule, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if len(data.Rules) > 0 {
		for _, item := range data.Rules {
			cBody := netconf.Body{}
			if !item.RuleId.IsNull() && !item.RuleId.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "id", strconv.FormatInt(item.RuleId.ValueInt64(), 10))
			}
			if !item.MatchingReplacementPattern.IsNull() && !item.MatchingReplacementPattern.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "matching-replacement-pattern", item.MatchingReplacementPattern.ValueString())
			}
			if !item.Reject.IsNull() && !item.Reject.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "reject", item.Reject.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/rule", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceTranslationRule) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	for i := range data.Rules {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.Rules[i].RuleId.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "id"); value.Exists() && !data.Rules[i].RuleId.IsNull() {
			data.Rules[i].RuleId = types.Int64Value(value.Int())
		} else {
			data.Rules[i].RuleId = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "matching-replacement-pattern"); value.Exists() && !data.Rules[i].MatchingReplacementPattern.IsNull() {
			data.Rules[i].MatchingReplacementPattern = types.StringValue(value.String())
		} else {
			data.Rules[i].MatchingReplacementPattern = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "reject"); value.Exists() && !data.Rules[i].Reject.IsNull() {
			data.Rules[i].Reject = types.StringValue(value.String())
		} else {
			data.Rules[i].Reject = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceTranslationRule) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule"); value.Exists() {
		data.Rules = make([]VoiceTranslationRuleRules, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceTranslationRuleRules{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.RuleId = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "matching-replacement-pattern"); cValue.Exists() {
				item.MatchingReplacementPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "reject"); cValue.Exists() {
				item.Reject = types.StringValue(cValue.String())
			}
			data.Rules = append(data.Rules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceTranslationRuleData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rule"); value.Exists() {
		data.Rules = make([]VoiceTranslationRuleRulesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceTranslationRuleRulesData{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.RuleId = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "matching-replacement-pattern"); cValue.Exists() {
				item.MatchingReplacementPattern = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "reject"); cValue.Exists() {
				item.Reject = types.StringValue(cValue.String())
			}
			data.Rules = append(data.Rules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceTranslationRule) addDeletedItemsXML(ctx context.Context, state VoiceTranslationRule, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Rules {
		stateKeys := [...]string{"id"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Rules[i].RuleId.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Rules[i].RuleId.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Rules {
			found = true
			if state.Rules[i].RuleId.ValueInt64() != data.Rules[j].RuleId.ValueInt64() {
				found = false
			}
			if found {
				if !state.Rules[i].Reject.IsNull() && data.Rules[j].Reject.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/reject", predicates))
				}
				if !state.Rules[i].MatchingReplacementPattern.IsNull() && data.Rules[j].MatchingReplacementPattern.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v/matching-replacement-pattern", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/rule%v", predicates))
		}
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceTranslationRule) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Rules {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.Rules[i].RuleId.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/rule%v", predicates))
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
