// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassSIPHeaderPassthrulist struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	DeleteMode        types.String `tfsdk:"delete_mode"`
	Tag               types.Int64  `tfsdk:"tag"`
	PassthruHeaders   types.List   `tfsdk:"passthru_headers"`
	PassthruHdrUnsupp types.Bool   `tfsdk:"passthru_hdr_unsupp"`
}

type VoiceClassSIPHeaderPassthrulistData struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	Tag               types.Int64  `tfsdk:"tag"`
	PassthruHeaders   types.List   `tfsdk:"passthru_headers"`
	PassthruHdrUnsupp types.Bool   `tfsdk:"passthru_hdr_unsupp"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassSIPHeaderPassthrulist) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-hdr-passthrulist=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassSIPHeaderPassthrulistData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-hdr-passthrulist=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassSIPHeaderPassthrulist) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-hdr-passthrulist[sip-hdr-passthrulist-tag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassSIPHeaderPassthrulistData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-hdr-passthrulist[sip-hdr-passthrulist-tag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassSIPHeaderPassthrulist) toBodyXML(ctx context.Context, config VoiceClassSIPHeaderPassthrulist) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassSIPHeaderPassthrulist) addToBodyXML(ctx context.Context, config VoiceClassSIPHeaderPassthrulist, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/sip-hdr-passthrulist-tag", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if !data.PassthruHeaders.IsNull() && !data.PassthruHeaders.IsUnknown() {
		var values []string
		data.PassthruHeaders.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/passthru-hdr", v)
		}
	}
	if !data.PassthruHdrUnsupp.IsNull() && !data.PassthruHdrUnsupp.IsUnknown() {
		if data.PassthruHdrUnsupp.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/passthru-hdr-unsupp", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/passthru-hdr-unsupp")
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassSIPHeaderPassthrulist) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-hdr-passthrulist-tag"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr"); value.Exists() && !data.PassthruHeaders.IsNull() {
		data.PassthruHeaders = helpers.GetStringListXML(value.Array())
	} else {
		data.PassthruHeaders = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr-unsupp"); !data.PassthruHdrUnsupp.IsNull() {
		if value.Exists() {
			data.PassthruHdrUnsupp = types.BoolValue(true)
		} else {
			data.PassthruHdrUnsupp = types.BoolValue(false)
		}
	} else {
		data.PassthruHdrUnsupp = types.BoolNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassSIPHeaderPassthrulist) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr"); value.Exists() {
		data.PassthruHeaders = helpers.GetStringListXML(value.Array())
	} else {
		data.PassthruHeaders = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr-unsupp"); value.Exists() {
		data.PassthruHdrUnsupp = types.BoolValue(true)
	} else {
		data.PassthruHdrUnsupp = types.BoolValue(false)
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassSIPHeaderPassthrulistData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr"); value.Exists() {
		data.PassthruHeaders = helpers.GetStringListXML(value.Array())
	} else {
		data.PassthruHeaders = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/passthru-hdr-unsupp"); value.Exists() {
		data.PassthruHdrUnsupp = types.BoolValue(true)
	} else {
		data.PassthruHdrUnsupp = types.BoolValue(false)
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassSIPHeaderPassthrulist) addDeletedItemsXML(ctx context.Context, state VoiceClassSIPHeaderPassthrulist, body string) string {
	b := netconf.NewBody(body)
	if !state.PassthruHdrUnsupp.IsNull() && data.PassthruHdrUnsupp.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/passthru-hdr-unsupp")
	}
	if !state.PassthruHeaders.IsNull() {
		if data.PassthruHeaders.IsNull() {
			var values []string
			state.PassthruHeaders.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/passthru-hdr[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.PassthruHeaders.ElementsAs(ctx, &dataValues, false)
			state.PassthruHeaders.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/passthru-hdr[.=%v]", v))
				}
			}
		}
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassSIPHeaderPassthrulist) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.PassthruHdrUnsupp.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/passthru-hdr-unsupp")
	}
	if !data.PassthruHeaders.IsNull() {
		var values []string
		data.PassthruHeaders.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/passthru-hdr[.=%v]", v))
		}
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
