// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassMedia struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	DeleteMode      types.String `tfsdk:"delete_mode"`
	Tag             types.Int64  `tfsdk:"tag"`
	AntiTrombone    types.Bool   `tfsdk:"anti_trombone"`
	Forking         types.Bool   `tfsdk:"forking"`
	MonitorVideo    types.Bool   `tfsdk:"monitor_video"`
	StatsDisconnect types.Bool   `tfsdk:"stats_disconnect"`
	Flow            types.String `tfsdk:"flow"`
}

type VoiceClassMediaData struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	Tag             types.Int64  `tfsdk:"tag"`
	AntiTrombone    types.Bool   `tfsdk:"anti_trombone"`
	Forking         types.Bool   `tfsdk:"forking"`
	MonitorVideo    types.Bool   `tfsdk:"monitor_video"`
	StatsDisconnect types.Bool   `tfsdk:"stats_disconnect"`
	Flow            types.String `tfsdk:"flow"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassMedia) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/media=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassMediaData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/media=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassMedia) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/media[media-tag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassMediaData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/media[media-tag=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassMedia) toBodyXML(ctx context.Context, config VoiceClassMedia) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassMedia) addToBodyXML(ctx context.Context, config VoiceClassMedia, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/media-tag", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if !data.AntiTrombone.IsNull() && !data.AntiTrombone.IsUnknown() {
		if data.AntiTrombone.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/media/anti-trombone", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/media/anti-trombone")
		}
	}
	if !data.Forking.IsNull() && !data.Forking.IsUnknown() {
		if data.Forking.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/media/forking", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/media/forking")
		}
	}
	if !data.MonitorVideo.IsNull() && !data.MonitorVideo.IsUnknown() {
		if data.MonitorVideo.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/media/monitor-video", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/media/monitor-video")
		}
	}
	if !data.StatsDisconnect.IsNull() && !data.StatsDisconnect.IsUnknown() {
		if data.StatsDisconnect.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/media/stats-disconnect", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/media/stats-disconnect")
		}
	}
	if !data.Flow.IsNull() && !data.Flow.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/media/flow-through-or-around", data.Flow.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassMedia) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media-tag"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/anti-trombone"); !data.AntiTrombone.IsNull() {
		if value.Exists() {
			data.AntiTrombone = types.BoolValue(true)
		} else {
			data.AntiTrombone = types.BoolValue(false)
		}
	} else {
		data.AntiTrombone = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/forking"); !data.Forking.IsNull() {
		if value.Exists() {
			data.Forking = types.BoolValue(true)
		} else {
			data.Forking = types.BoolValue(false)
		}
	} else {
		data.Forking = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/monitor-video"); !data.MonitorVideo.IsNull() {
		if value.Exists() {
			data.MonitorVideo = types.BoolValue(true)
		} else {
			data.MonitorVideo = types.BoolValue(false)
		}
	} else {
		data.MonitorVideo = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/stats-disconnect"); !data.StatsDisconnect.IsNull() {
		if value.Exists() {
			data.StatsDisconnect = types.BoolValue(true)
		} else {
			data.StatsDisconnect = types.BoolValue(false)
		}
	} else {
		data.StatsDisconnect = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/flow-through-or-around"); value.Exists() && !data.Flow.IsNull() {
		data.Flow = types.StringValue(value.String())
	} else {
		data.Flow = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassMedia) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/anti-trombone"); value.Exists() {
		data.AntiTrombone = types.BoolValue(true)
	} else {
		data.AntiTrombone = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/forking"); value.Exists() {
		data.Forking = types.BoolValue(true)
	} else {
		data.Forking = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/monitor-video"); value.Exists() {
		data.MonitorVideo = types.BoolValue(true)
	} else {
		data.MonitorVideo = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/stats-disconnect"); value.Exists() {
		data.StatsDisconnect = types.BoolValue(true)
	} else {
		data.StatsDisconnect = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/flow-through-or-around"); value.Exists() {
		data.Flow = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassMediaData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/anti-trombone"); value.Exists() {
		data.AntiTrombone = types.BoolValue(true)
	} else {
		data.AntiTrombone = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/forking"); value.Exists() {
		data.Forking = types.BoolValue(true)
	} else {
		data.Forking = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/monitor-video"); value.Exists() {
		data.MonitorVideo = types.BoolValue(true)
	} else {
		data.MonitorVideo = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/stats-disconnect"); value.Exists() {
		data.StatsDisconnect = types.BoolValue(true)
	} else {
		data.StatsDisconnect = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/media/flow-through-or-around"); value.Exists() {
		data.Flow = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassMedia) addDeletedItemsXML(ctx context.Context, state VoiceClassMedia, body string) string {
	b := netconf.NewBody(body)
	if !state.Flow.IsNull() && data.Flow.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/media/flow-through-or-around")
	}
	if !state.StatsDisconnect.IsNull() && data.StatsDisconnect.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/media/stats-disconnect")
	}
	if !state.MonitorVideo.IsNull() && data.MonitorVideo.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/media/monitor-video")
	}
	if !state.Forking.IsNull() && data.Forking.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/media/forking")
	}
	if !state.AntiTrombone.IsNull() && data.AntiTrombone.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/media/anti-trombone")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassMedia) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.Flow.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/media/flow-through-or-around")
	}
	if !data.StatsDisconnect.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/media/stats-disconnect")
	}
	if !data.MonitorVideo.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/media/monitor-video")
	}
	if !data.Forking.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/media/forking")
	}
	if !data.AntiTrombone.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/media/anti-trombone")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
