// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassServerGroup struct {
	Device               types.String                        `tfsdk:"device"`
	Id                   types.String                        `tfsdk:"id"`
	DeleteMode           types.String                        `tfsdk:"delete_mode"`
	Tag                  types.Int64                         `tfsdk:"tag"`
	Description          types.String                        `tfsdk:"description"`
	Shutdown             types.Bool                          `tfsdk:"shutdown"`
	HuntSchemeRoundRobin types.Bool                          `tfsdk:"hunt_scheme_round_robin"`
	Ipv4                 []VoiceClassServerGroupIpv4         `tfsdk:"ipv4"`
	Ipv4WithPort         []VoiceClassServerGroupIpv4WithPort `tfsdk:"ipv4_with_port"`
}
type VoiceClassServerGroupIpv4 struct {
	Address    types.String `tfsdk:"address"`
	Preference types.Int64  `tfsdk:"preference"`
}
type VoiceClassServerGroupIpv4WithPort struct {
	Address    types.String `tfsdk:"address"`
	Port       types.Int64  `tfsdk:"port"`
	Preference types.Int64  `tfsdk:"preference"`
}

type VoiceClassServerGroupData struct {
	Device               types.String                            `tfsdk:"device"`
	Id                   types.String                            `tfsdk:"id"`
	Tag                  types.Int64                             `tfsdk:"tag"`
	Description          types.String                            `tfsdk:"description"`
	Shutdown             types.Bool                              `tfsdk:"shutdown"`
	HuntSchemeRoundRobin types.Bool                              `tfsdk:"hunt_scheme_round_robin"`
	Ipv4                 []VoiceClassServerGroupIpv4Data         `tfsdk:"ipv4"`
	Ipv4WithPort         []VoiceClassServerGroupIpv4WithPortData `tfsdk:"ipv4_with_port"`
}
type VoiceClassServerGroupIpv4Data struct {
	Address    types.String `tfsdk:"address"`
	Preference types.Int64  `tfsdk:"preference"`
}
type VoiceClassServerGroupIpv4WithPortData struct {
	Address    types.String `tfsdk:"address"`
	Port       types.Int64  `tfsdk:"port"`
	Preference types.Int64  `tfsdk:"preference"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassServerGroup) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/server-group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassServerGroupData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/server-group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassServerGroup) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/server-group[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassServerGroupData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/server-group[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassServerGroup) toBodyXML(ctx context.Context, config VoiceClassServerGroup) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassServerGroup) addToBodyXML(ctx context.Context, config VoiceClassServerGroup, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if !data.Shutdown.IsNull() && !data.Shutdown.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/shutdown", data.Shutdown.ValueBool())
	}
	if !data.HuntSchemeRoundRobin.IsNull() && !data.HuntSchemeRoundRobin.IsUnknown() {
		if data.HuntSchemeRoundRobin.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/hunt-scheme/round-robin", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/hunt-scheme/round-robin")
		}
	}
	if len(data.Ipv4) > 0 {
		for _, item := range data.Ipv4 {
			cBody := netconf.Body{}
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "address", item.Address.ValueString())
			}
			if !item.Preference.IsNull() && !item.Preference.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "preference", strconv.FormatInt(item.Preference.ValueInt64(), 10))
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/ipv4-address/ipv4", cBody.Res())
		}
	}
	if len(data.Ipv4WithPort) > 0 {
		for _, item := range data.Ipv4WithPort {
			cBody := netconf.Body{}
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "address", item.Address.ValueString())
			}
			if !item.Port.IsNull() && !item.Port.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "port", strconv.FormatInt(item.Port.ValueInt64(), 10))
			}
			if !item.Preference.IsNull() && !item.Preference.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "preference", strconv.FormatInt(item.Preference.ValueInt64(), 10))
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassServerGroup) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/shutdown"); !data.Shutdown.IsNull() {
		if value.Exists() {
			data.Shutdown = types.BoolValue(value.Bool())
		}
	} else {
		data.Shutdown = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/round-robin"); !data.HuntSchemeRoundRobin.IsNull() {
		if value.Exists() {
			data.HuntSchemeRoundRobin = types.BoolValue(true)
		} else {
			data.HuntSchemeRoundRobin = types.BoolValue(false)
		}
	} else {
		data.HuntSchemeRoundRobin = types.BoolNull()
	}
	for i := range data.Ipv4 {
		keys := [...]string{"address"}
		keyValues := [...]string{data.Ipv4[i].Address.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "address"); value.Exists() && !data.Ipv4[i].Address.IsNull() {
			data.Ipv4[i].Address = types.StringValue(value.String())
		} else {
			data.Ipv4[i].Address = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "preference"); value.Exists() && !data.Ipv4[i].Preference.IsNull() {
			data.Ipv4[i].Preference = types.Int64Value(value.Int())
		} else {
			data.Ipv4[i].Preference = types.Int64Null()
		}
	}
	for i := range data.Ipv4WithPort {
		keys := [...]string{"address", "port"}
		keyValues := [...]string{data.Ipv4WithPort[i].Address.ValueString(), strconv.FormatInt(data.Ipv4WithPort[i].Port.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "address"); value.Exists() && !data.Ipv4WithPort[i].Address.IsNull() {
			data.Ipv4WithPort[i].Address = types.StringValue(value.String())
		} else {
			data.Ipv4WithPort[i].Address = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "port"); value.Exists() && !data.Ipv4WithPort[i].Port.IsNull() {
			data.Ipv4WithPort[i].Port = types.Int64Value(value.Int())
		} else {
			data.Ipv4WithPort[i].Port = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "preference"); value.Exists() && !data.Ipv4WithPort[i].Preference.IsNull() {
			data.Ipv4WithPort[i].Preference = types.Int64Value(value.Int())
		} else {
			data.Ipv4WithPort[i].Preference = types.Int64Null()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassServerGroup) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/shutdown"); value.Exists() {
		data.Shutdown = types.BoolValue(value.Bool())
	} else {
		data.Shutdown = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/round-robin"); value.Exists() {
		data.HuntSchemeRoundRobin = types.BoolValue(true)
	} else {
		data.HuntSchemeRoundRobin = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4"); value.Exists() {
		data.Ipv4 = make([]VoiceClassServerGroupIpv4, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassServerGroupIpv4{}
			if cValue := helpers.GetFromXPath(v, "address"); cValue.Exists() {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			data.Ipv4 = append(data.Ipv4, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4"); value.Exists() {
		data.Ipv4WithPort = make([]VoiceClassServerGroupIpv4WithPort, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassServerGroupIpv4WithPort{}
			if cValue := helpers.GetFromXPath(v, "address"); cValue.Exists() {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "port"); cValue.Exists() {
				item.Port = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			data.Ipv4WithPort = append(data.Ipv4WithPort, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassServerGroupData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/shutdown"); value.Exists() {
		data.Shutdown = types.BoolValue(value.Bool())
	} else {
		data.Shutdown = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hunt-scheme/round-robin"); value.Exists() {
		data.HuntSchemeRoundRobin = types.BoolValue(true)
	} else {
		data.HuntSchemeRoundRobin = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4"); value.Exists() {
		data.Ipv4 = make([]VoiceClassServerGroupIpv4Data, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassServerGroupIpv4Data{}
			if cValue := helpers.GetFromXPath(v, "address"); cValue.Exists() {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			data.Ipv4 = append(data.Ipv4, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4"); value.Exists() {
		data.Ipv4WithPort = make([]VoiceClassServerGroupIpv4WithPortData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := VoiceClassServerGroupIpv4WithPortData{}
			if cValue := helpers.GetFromXPath(v, "address"); cValue.Exists() {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "port"); cValue.Exists() {
				item.Port = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "preference"); cValue.Exists() {
				item.Preference = types.Int64Value(cValue.Int())
			}
			data.Ipv4WithPort = append(data.Ipv4WithPort, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassServerGroup) addDeletedItemsXML(ctx context.Context, state VoiceClassServerGroup, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Ipv4WithPort {
		stateKeys := [...]string{"address", "port"}
		stateKeyValues := [...]string{state.Ipv4WithPort[i].Address.ValueString(), strconv.FormatInt(state.Ipv4WithPort[i].Port.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Ipv4WithPort[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.Ipv4WithPort[i].Port.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Ipv4WithPort {
			found = true
			if state.Ipv4WithPort[i].Address.ValueString() != data.Ipv4WithPort[j].Address.ValueString() {
				found = false
			}
			if state.Ipv4WithPort[i].Port.ValueInt64() != data.Ipv4WithPort[j].Port.ValueInt64() {
				found = false
			}
			if found {
				if !state.Ipv4WithPort[i].Preference.IsNull() && data.Ipv4WithPort[j].Preference.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4%v/preference", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4%v", predicates))
		}
	}
	for i := range state.Ipv4 {
		stateKeys := [...]string{"address"}
		stateKeyValues := [...]string{state.Ipv4[i].Address.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Ipv4[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Ipv4 {
			found = true
			if state.Ipv4[i].Address.ValueString() != data.Ipv4[j].Address.ValueString() {
				found = false
			}
			if found {
				if !state.Ipv4[i].Preference.IsNull() && data.Ipv4[j].Preference.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/ipv4-address/ipv4%v/preference", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/ipv4-address/ipv4%v", predicates))
		}
	}
	if !state.HuntSchemeRoundRobin.IsNull() && data.HuntSchemeRoundRobin.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/hunt-scheme/round-robin")
	}
	if !state.Shutdown.IsNull() && data.Shutdown.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/shutdown")
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassServerGroup) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Ipv4WithPort {
		keys := [...]string{"address", "port"}
		keyValues := [...]string{data.Ipv4WithPort[i].Address.ValueString(), strconv.FormatInt(data.Ipv4WithPort[i].Port.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/ipv4-address/ipv4-addr-port/ipv4%v", predicates))
	}
	for i := range data.Ipv4 {
		keys := [...]string{"address"}
		keyValues := [...]string{data.Ipv4[i].Address.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/ipv4-address/ipv4%v", predicates))
	}
	if !data.HuntSchemeRoundRobin.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/hunt-scheme/round-robin")
	}
	if !data.Shutdown.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/shutdown")
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
