// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type VoiceClassSIPCopylist struct {
	Device              types.String `tfsdk:"device"`
	Id                  types.String `tfsdk:"id"`
	DeleteMode          types.String `tfsdk:"delete_mode"`
	Tag                 types.Int64  `tfsdk:"tag"`
	SipHeaderReqUri     types.Bool   `tfsdk:"sip_header_req_uri"`
	SipHeaderStatusLine types.Bool   `tfsdk:"sip_header_status_line"`
	Headers             types.Set    `tfsdk:"headers"`
}

type VoiceClassSIPCopylistData struct {
	Device              types.String `tfsdk:"device"`
	Id                  types.String `tfsdk:"id"`
	Tag                 types.Int64  `tfsdk:"tag"`
	SipHeaderReqUri     types.Bool   `tfsdk:"sip_header_req_uri"`
	SipHeaderStatusLine types.Bool   `tfsdk:"sip_header_status_line"`
	Headers             types.Set    `tfsdk:"headers"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VoiceClassSIPCopylist) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-copylist=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

func (data VoiceClassSIPCopylistData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-copylist=%v", url.QueryEscape(fmt.Sprintf("%v", data.Tag.ValueInt64())))
}

// getXPath returns the XPath for NETCONF operations
func (data VoiceClassSIPCopylist) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-copylist[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

func (data VoiceClassSIPCopylistData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:voice/class/sip-copylist[id=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Tag.ValueInt64()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data VoiceClassSIPCopylist) toBodyXML(ctx context.Context, config VoiceClassSIPCopylist) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data VoiceClassSIPCopylist) addToBodyXML(ctx context.Context, config VoiceClassSIPCopylist, body netconf.Body) netconf.Body {
	if !data.Tag.IsNull() && !data.Tag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", strconv.FormatInt(data.Tag.ValueInt64(), 10))
	}
	if !data.SipHeaderReqUri.IsNull() && !data.SipHeaderReqUri.IsUnknown() {
		if data.SipHeaderReqUri.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/sip-header/SIP-Req-URI", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/sip-header/SIP-Req-URI")
		}
	}
	if !data.SipHeaderStatusLine.IsNull() && !data.SipHeaderStatusLine.IsUnknown() {
		if data.SipHeaderStatusLine.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/sip-header/SIP-StatusLine", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/sip-header/SIP-StatusLine")
		}
	}
	if !data.Headers.IsNull() && !data.Headers.IsUnknown() {
		var values []string
		data.Headers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/sip-header/header", v)
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *VoiceClassSIPCopylist) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Tag.IsNull() {
		data.Tag = types.Int64Value(value.Int())
	} else {
		data.Tag = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-Req-URI"); !data.SipHeaderReqUri.IsNull() {
		if value.Exists() {
			data.SipHeaderReqUri = types.BoolValue(true)
		} else {
			data.SipHeaderReqUri = types.BoolValue(false)
		}
	} else {
		data.SipHeaderReqUri = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-StatusLine"); !data.SipHeaderStatusLine.IsNull() {
		if value.Exists() {
			data.SipHeaderStatusLine = types.BoolValue(true)
		} else {
			data.SipHeaderStatusLine = types.BoolValue(false)
		}
	} else {
		data.SipHeaderStatusLine = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/header"); value.Exists() && !data.Headers.IsNull() {
		data.Headers = helpers.GetStringSetXML(value.Array())
	} else {
		data.Headers = types.SetNull(types.StringType)
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *VoiceClassSIPCopylist) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-Req-URI"); value.Exists() {
		data.SipHeaderReqUri = types.BoolValue(true)
	} else {
		data.SipHeaderReqUri = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-StatusLine"); value.Exists() {
		data.SipHeaderStatusLine = types.BoolValue(true)
	} else {
		data.SipHeaderStatusLine = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/header"); value.Exists() {
		data.Headers = helpers.GetStringSetXML(value.Array())
	} else {
		data.Headers = types.SetNull(types.StringType)
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *VoiceClassSIPCopylistData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-Req-URI"); value.Exists() {
		data.SipHeaderReqUri = types.BoolValue(true)
	} else {
		data.SipHeaderReqUri = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/SIP-StatusLine"); value.Exists() {
		data.SipHeaderStatusLine = types.BoolValue(true)
	} else {
		data.SipHeaderStatusLine = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sip-header/header"); value.Exists() {
		data.Headers = helpers.GetStringSetXML(value.Array())
	} else {
		data.Headers = types.SetNull(types.StringType)
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *VoiceClassSIPCopylist) addDeletedItemsXML(ctx context.Context, state VoiceClassSIPCopylist, body string) string {
	b := netconf.NewBody(body)
	if !state.Headers.IsNull() {
		if data.Headers.IsNull() {
			var values []string
			state.Headers.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sip-header/header[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.Headers.ElementsAs(ctx, &dataValues, false)
			state.Headers.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sip-header/header[.=%v]", v))
				}
			}
		}
	}
	if !state.SipHeaderStatusLine.IsNull() && data.SipHeaderStatusLine.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/sip-header/SIP-StatusLine")
	}
	if !state.SipHeaderReqUri.IsNull() && data.SipHeaderReqUri.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/sip-header/SIP-Req-URI")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *VoiceClassSIPCopylist) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.Headers.IsNull() {
		var values []string
		data.Headers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/sip-header/header[.=%v]", v))
		}
	}
	if !data.SipHeaderStatusLine.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/sip-header/SIP-StatusLine")
	}
	if !data.SipHeaderReqUri.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/sip-header/SIP-Req-URI")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
