// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type SCCP struct {
	Device         types.String     `tfsdk:"device"`
	Id             types.String     `tfsdk:"id"`
	DeleteMode     types.String     `tfsdk:"delete_mode"`
	LocalInterface types.String     `tfsdk:"local_interface"`
	IpPrecedence   types.Int64      `tfsdk:"ip_precedence"`
	CcmServers     []SCCPCcmServers `tfsdk:"ccm_servers"`
	CcmGroups      []SCCPCcmGroups  `tfsdk:"ccm_groups"`
}
type SCCPCcmServers struct {
	Host       types.String `tfsdk:"host"`
	Identifier types.Int64  `tfsdk:"identifier"`
	Version    types.String `tfsdk:"version"`
}
type SCCPCcmGroups struct {
	GroupId           types.Int64                      `tfsdk:"group_id"`
	Description       types.String                     `tfsdk:"description"`
	AssociateCcm      []SCCPCcmGroupsAssociateCcm      `tfsdk:"associate_ccm"`
	AssociateProfiles []SCCPCcmGroupsAssociateProfiles `tfsdk:"associate_profiles"`
}
type SCCPCcmGroupsAssociateCcm struct {
	CcmId    types.Int64 `tfsdk:"ccm_id"`
	Priority types.Int64 `tfsdk:"priority"`
}
type SCCPCcmGroupsAssociateProfiles struct {
	ProfileId types.String `tfsdk:"profile_id"`
	Register  types.String `tfsdk:"register"`
}

type SCCPData struct {
	Device         types.String         `tfsdk:"device"`
	Id             types.String         `tfsdk:"id"`
	LocalInterface types.String         `tfsdk:"local_interface"`
	IpPrecedence   types.Int64          `tfsdk:"ip_precedence"`
	CcmServers     []SCCPCcmServersData `tfsdk:"ccm_servers"`
	CcmGroups      []SCCPCcmGroupsData  `tfsdk:"ccm_groups"`
}
type SCCPCcmServersData struct {
	Host       types.String `tfsdk:"host"`
	Identifier types.Int64  `tfsdk:"identifier"`
	Version    types.String `tfsdk:"version"`
}
type SCCPCcmGroupsData struct {
	GroupId           types.Int64                          `tfsdk:"group_id"`
	Description       types.String                         `tfsdk:"description"`
	AssociateCcm      []SCCPCcmGroupsAssociateCcmData      `tfsdk:"associate_ccm"`
	AssociateProfiles []SCCPCcmGroupsAssociateProfilesData `tfsdk:"associate_profiles"`
}
type SCCPCcmGroupsAssociateCcmData struct {
	CcmId    types.Int64 `tfsdk:"ccm_id"`
	Priority types.Int64 `tfsdk:"priority"`
}
type SCCPCcmGroupsAssociateProfilesData struct {
	ProfileId types.String `tfsdk:"profile_id"`
	Register  types.String `tfsdk:"register"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data SCCP) getPath() string {
	return "Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:sccp-config"
}

func (data SCCPData) getPath() string {
	return "Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:sccp-config"
}

// getXPath returns the XPath for NETCONF operations
func (data SCCP) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:sccp-config"
	return path
}

func (data SCCPData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/Cisco-IOS-XE-voice:sccp-config"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data SCCP) toBodyXML(ctx context.Context, config SCCP) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data SCCP) addToBodyXML(ctx context.Context, config SCCP, body netconf.Body) netconf.Body {
	if !data.LocalInterface.IsNull() && !data.LocalInterface.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/sccp/local", data.LocalInterface.ValueString())
	}
	if !data.IpPrecedence.IsNull() && !data.IpPrecedence.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/sccp/ip/precedence", strconv.FormatInt(data.IpPrecedence.ValueInt64(), 10))
	}
	if len(data.CcmServers) > 0 {
		for _, item := range data.CcmServers {
			cBody := netconf.Body{}
			if !item.Host.IsNull() && !item.Host.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "host", item.Host.ValueString())
			}
			if !item.Identifier.IsNull() && !item.Identifier.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "identifier", strconv.FormatInt(item.Identifier.ValueInt64(), 10))
			}
			if !item.Version.IsNull() && !item.Version.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "version", item.Version.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/sccp/sccp-ccm-list/ccm", cBody.Res())
		}
	}
	if len(data.CcmGroups) > 0 {
		for _, item := range data.CcmGroups {
			cBody := netconf.Body{}
			if !item.GroupId.IsNull() && !item.GroupId.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "id", strconv.FormatInt(item.GroupId.ValueInt64(), 10))
			}
			if !item.Description.IsNull() && !item.Description.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "description", item.Description.ValueString())
			}
			if len(item.AssociateCcm) > 0 {
				for _, citem := range item.AssociateCcm {
					ccBody := netconf.Body{}
					if !citem.CcmId.IsNull() && !citem.CcmId.IsUnknown() {
						ccBody = helpers.SetFromXPath(ccBody, "id", strconv.FormatInt(citem.CcmId.ValueInt64(), 10))
					}
					if !citem.Priority.IsNull() && !citem.Priority.IsUnknown() {
						ccBody = helpers.SetFromXPath(ccBody, "priority", strconv.FormatInt(citem.Priority.ValueInt64(), 10))
					}
					cBody = helpers.SetRawFromXPath(cBody, "associate/ccm", ccBody.Res())
				}
			}
			if len(item.AssociateProfiles) > 0 {
				for _, citem := range item.AssociateProfiles {
					ccBody := netconf.Body{}
					if !citem.ProfileId.IsNull() && !citem.ProfileId.IsUnknown() {
						ccBody = helpers.SetFromXPath(ccBody, "id", citem.ProfileId.ValueString())
					}
					if !citem.Register.IsNull() && !citem.Register.IsUnknown() {
						ccBody = helpers.SetFromXPath(ccBody, "register", citem.Register.ValueString())
					}
					cBody = helpers.SetRawFromXPath(cBody, "associate/profile", ccBody.Res())
				}
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *SCCP) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/local"); value.Exists() && !data.LocalInterface.IsNull() {
		data.LocalInterface = types.StringValue(value.String())
	} else {
		data.LocalInterface = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/ip/precedence"); value.Exists() && !data.IpPrecedence.IsNull() {
		data.IpPrecedence = types.Int64Value(value.Int())
	} else {
		data.IpPrecedence = types.Int64Null()
	}
	for i := range data.CcmServers {
		keys := [...]string{"host"}
		keyValues := [...]string{data.CcmServers[i].Host.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-list/ccm").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "host"); value.Exists() && !data.CcmServers[i].Host.IsNull() {
			data.CcmServers[i].Host = types.StringValue(value.String())
		} else {
			data.CcmServers[i].Host = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "identifier"); value.Exists() && !data.CcmServers[i].Identifier.IsNull() {
			data.CcmServers[i].Identifier = types.Int64Value(value.Int())
		} else {
			data.CcmServers[i].Identifier = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "version"); value.Exists() && !data.CcmServers[i].Version.IsNull() {
			data.CcmServers[i].Version = types.StringValue(value.String())
		} else {
			data.CcmServers[i].Version = types.StringNull()
		}
	}
	for i := range data.CcmGroups {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.CcmGroups[i].GroupId.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "id"); value.Exists() && !data.CcmGroups[i].GroupId.IsNull() {
			data.CcmGroups[i].GroupId = types.Int64Value(value.Int())
		} else {
			data.CcmGroups[i].GroupId = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "description"); value.Exists() && !data.CcmGroups[i].Description.IsNull() {
			data.CcmGroups[i].Description = types.StringValue(value.String())
		} else {
			data.CcmGroups[i].Description = types.StringNull()
		}
		for ci := range data.CcmGroups[i].AssociateCcm {
			keys := [...]string{"id"}
			keyValues := [...]string{strconv.FormatInt(data.CcmGroups[i].AssociateCcm[ci].CcmId.ValueInt64(), 10)}

			var cr xmldot.Result
			helpers.GetFromXPath(r, "associate/ccm").ForEach(
				func(_ int, v xmldot.Result) bool {
					found := false
					for ik := range keys {
						if v.Get(keys[ik]).String() == keyValues[ik] {
							found = true
							continue
						}
						found = false
						break
					}
					if found {
						cr = v
						return false
					}
					return true
				},
			)
			if value := helpers.GetFromXPath(cr, "id"); value.Exists() && !data.CcmGroups[i].AssociateCcm[ci].CcmId.IsNull() {
				data.CcmGroups[i].AssociateCcm[ci].CcmId = types.Int64Value(value.Int())
			} else {
				data.CcmGroups[i].AssociateCcm[ci].CcmId = types.Int64Null()
			}
			if value := helpers.GetFromXPath(cr, "priority"); value.Exists() && !data.CcmGroups[i].AssociateCcm[ci].Priority.IsNull() {
				data.CcmGroups[i].AssociateCcm[ci].Priority = types.Int64Value(value.Int())
			} else {
				data.CcmGroups[i].AssociateCcm[ci].Priority = types.Int64Null()
			}
		}
		for ci := range data.CcmGroups[i].AssociateProfiles {
			keys := [...]string{"id"}
			keyValues := [...]string{data.CcmGroups[i].AssociateProfiles[ci].ProfileId.ValueString()}

			var cr xmldot.Result
			helpers.GetFromXPath(r, "associate/profile").ForEach(
				func(_ int, v xmldot.Result) bool {
					found := false
					for ik := range keys {
						if v.Get(keys[ik]).String() == keyValues[ik] {
							found = true
							continue
						}
						found = false
						break
					}
					if found {
						cr = v
						return false
					}
					return true
				},
			)
			if value := helpers.GetFromXPath(cr, "id"); value.Exists() && !data.CcmGroups[i].AssociateProfiles[ci].ProfileId.IsNull() {
				data.CcmGroups[i].AssociateProfiles[ci].ProfileId = types.StringValue(value.String())
			} else {
				data.CcmGroups[i].AssociateProfiles[ci].ProfileId = types.StringNull()
			}
			if value := helpers.GetFromXPath(cr, "register"); value.Exists() && !data.CcmGroups[i].AssociateProfiles[ci].Register.IsNull() {
				data.CcmGroups[i].AssociateProfiles[ci].Register = types.StringValue(value.String())
			} else {
				data.CcmGroups[i].AssociateProfiles[ci].Register = types.StringNull()
			}
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *SCCP) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/local"); value.Exists() {
		data.LocalInterface = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/ip/precedence"); value.Exists() {
		data.IpPrecedence = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-list/ccm"); value.Exists() {
		data.CcmServers = make([]SCCPCcmServers, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SCCPCcmServers{}
			if cValue := helpers.GetFromXPath(v, "host"); cValue.Exists() {
				item.Host = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "identifier"); cValue.Exists() {
				item.Identifier = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "version"); cValue.Exists() {
				item.Version = types.StringValue(cValue.String())
			}
			data.CcmServers = append(data.CcmServers, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group"); value.Exists() {
		data.CcmGroups = make([]SCCPCcmGroups, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SCCPCcmGroups{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.GroupId = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "description"); cValue.Exists() {
				item.Description = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "associate/ccm"); cValue.Exists() {
				item.AssociateCcm = make([]SCCPCcmGroupsAssociateCcm, 0)
				cValue.ForEach(func(_ int, cv xmldot.Result) bool {
					cItem := SCCPCcmGroupsAssociateCcm{}
					if ccValue := helpers.GetFromXPath(cv, "id"); ccValue.Exists() {
						cItem.CcmId = types.Int64Value(ccValue.Int())
					}
					if ccValue := helpers.GetFromXPath(cv, "priority"); ccValue.Exists() {
						cItem.Priority = types.Int64Value(ccValue.Int())
					}
					item.AssociateCcm = append(item.AssociateCcm, cItem)
					return true
				})
			}
			if cValue := helpers.GetFromXPath(v, "associate/profile"); cValue.Exists() {
				item.AssociateProfiles = make([]SCCPCcmGroupsAssociateProfiles, 0)
				cValue.ForEach(func(_ int, cv xmldot.Result) bool {
					cItem := SCCPCcmGroupsAssociateProfiles{}
					if ccValue := helpers.GetFromXPath(cv, "id"); ccValue.Exists() {
						cItem.ProfileId = types.StringValue(ccValue.String())
					}
					if ccValue := helpers.GetFromXPath(cv, "register"); ccValue.Exists() {
						cItem.Register = types.StringValue(ccValue.String())
					}
					item.AssociateProfiles = append(item.AssociateProfiles, cItem)
					return true
				})
			}
			data.CcmGroups = append(data.CcmGroups, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *SCCPData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/local"); value.Exists() {
		data.LocalInterface = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/ip/precedence"); value.Exists() {
		data.IpPrecedence = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-list/ccm"); value.Exists() {
		data.CcmServers = make([]SCCPCcmServersData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SCCPCcmServersData{}
			if cValue := helpers.GetFromXPath(v, "host"); cValue.Exists() {
				item.Host = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "identifier"); cValue.Exists() {
				item.Identifier = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "version"); cValue.Exists() {
				item.Version = types.StringValue(cValue.String())
			}
			data.CcmServers = append(data.CcmServers, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group"); value.Exists() {
		data.CcmGroups = make([]SCCPCcmGroupsData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SCCPCcmGroupsData{}
			if cValue := helpers.GetFromXPath(v, "id"); cValue.Exists() {
				item.GroupId = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "description"); cValue.Exists() {
				item.Description = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "associate/ccm"); cValue.Exists() {
				item.AssociateCcm = make([]SCCPCcmGroupsAssociateCcmData, 0)
				cValue.ForEach(func(_ int, cv xmldot.Result) bool {
					cItem := SCCPCcmGroupsAssociateCcmData{}
					if ccValue := helpers.GetFromXPath(cv, "id"); ccValue.Exists() {
						cItem.CcmId = types.Int64Value(ccValue.Int())
					}
					if ccValue := helpers.GetFromXPath(cv, "priority"); ccValue.Exists() {
						cItem.Priority = types.Int64Value(ccValue.Int())
					}
					item.AssociateCcm = append(item.AssociateCcm, cItem)
					return true
				})
			}
			if cValue := helpers.GetFromXPath(v, "associate/profile"); cValue.Exists() {
				item.AssociateProfiles = make([]SCCPCcmGroupsAssociateProfilesData, 0)
				cValue.ForEach(func(_ int, cv xmldot.Result) bool {
					cItem := SCCPCcmGroupsAssociateProfilesData{}
					if ccValue := helpers.GetFromXPath(cv, "id"); ccValue.Exists() {
						cItem.ProfileId = types.StringValue(ccValue.String())
					}
					if ccValue := helpers.GetFromXPath(cv, "register"); ccValue.Exists() {
						cItem.Register = types.StringValue(ccValue.String())
					}
					item.AssociateProfiles = append(item.AssociateProfiles, cItem)
					return true
				})
			}
			data.CcmGroups = append(data.CcmGroups, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *SCCP) addDeletedItemsXML(ctx context.Context, state SCCP, body string) string {
	b := netconf.NewBody(body)
	for i := range state.CcmGroups {
		stateKeys := [...]string{"id"}
		stateKeyValues := [...]string{strconv.FormatInt(state.CcmGroups[i].GroupId.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.CcmGroups[i].GroupId.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.CcmGroups {
			found = true
			if state.CcmGroups[i].GroupId.ValueInt64() != data.CcmGroups[j].GroupId.ValueInt64() {
				found = false
			}
			if found {
				for ci := range state.CcmGroups[i].AssociateProfiles {
					cstateKeys := [...]string{"id"}
					cstateKeyValues := [...]string{state.CcmGroups[i].AssociateProfiles[ci].ProfileId.ValueString()}
					cpredicates := ""
					for i := range cstateKeys {
						cpredicates += fmt.Sprintf("[%s='%s']", cstateKeys[i], cstateKeyValues[i])
					}

					cemptyKeys := true
					if !reflect.ValueOf(state.CcmGroups[i].AssociateProfiles[ci].ProfileId.ValueString()).IsZero() {
						cemptyKeys = false
					}
					if cemptyKeys {
						continue
					}

					found := false
					for cj := range data.CcmGroups[j].AssociateProfiles {
						found = true
						if state.CcmGroups[i].AssociateProfiles[ci].ProfileId.ValueString() != data.CcmGroups[j].AssociateProfiles[cj].ProfileId.ValueString() {
							found = false
						}
						if found {
							if !state.CcmGroups[i].AssociateProfiles[ci].Register.IsNull() && data.CcmGroups[j].AssociateProfiles[cj].Register.IsNull() {
								b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v/associate/profile%v/register", predicates, cpredicates))
							}
							break
						}
					}
					if !found {
						b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v/associate/profile%v", predicates, cpredicates))
					}
				}
				for ci := range state.CcmGroups[i].AssociateCcm {
					cstateKeys := [...]string{"id"}
					cstateKeyValues := [...]string{strconv.FormatInt(state.CcmGroups[i].AssociateCcm[ci].CcmId.ValueInt64(), 10)}
					cpredicates := ""
					for i := range cstateKeys {
						cpredicates += fmt.Sprintf("[%s='%s']", cstateKeys[i], cstateKeyValues[i])
					}

					cemptyKeys := true
					if !reflect.ValueOf(state.CcmGroups[i].AssociateCcm[ci].CcmId.ValueInt64()).IsZero() {
						cemptyKeys = false
					}
					if cemptyKeys {
						continue
					}

					found := false
					for cj := range data.CcmGroups[j].AssociateCcm {
						found = true
						if state.CcmGroups[i].AssociateCcm[ci].CcmId.ValueInt64() != data.CcmGroups[j].AssociateCcm[cj].CcmId.ValueInt64() {
							found = false
						}
						if found {
							if !state.CcmGroups[i].AssociateCcm[ci].Priority.IsNull() && data.CcmGroups[j].AssociateCcm[cj].Priority.IsNull() {
								b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v/associate/ccm%v/priority", predicates, cpredicates))
							}
							break
						}
					}
					if !found {
						b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v/associate/ccm%v", predicates, cpredicates))
					}
				}
				if !state.CcmGroups[i].Description.IsNull() && data.CcmGroups[j].Description.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v/description", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v", predicates))
		}
	}
	for i := range state.CcmServers {
		stateKeys := [...]string{"host"}
		stateKeyValues := [...]string{state.CcmServers[i].Host.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.CcmServers[i].Host.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.CcmServers {
			found = true
			if state.CcmServers[i].Host.ValueString() != data.CcmServers[j].Host.ValueString() {
				found = false
			}
			if found {
				if !state.CcmServers[i].Version.IsNull() && data.CcmServers[j].Version.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-list/ccm%v/version", predicates))
				}
				if !state.CcmServers[i].Identifier.IsNull() && data.CcmServers[j].Identifier.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-list/ccm%v/identifier", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/sccp/sccp-ccm-list/ccm%v", predicates))
		}
	}
	if !state.IpPrecedence.IsNull() && data.IpPrecedence.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/sccp/ip/precedence")
	}
	if !state.LocalInterface.IsNull() && data.LocalInterface.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/sccp/local")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *SCCP) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.CcmGroups {
		keys := [...]string{"id"}
		keyValues := [...]string{strconv.FormatInt(data.CcmGroups[i].GroupId.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/sccp/sccp-ccm-group-list/ccm/group%v", predicates))
	}
	for i := range data.CcmServers {
		keys := [...]string{"host"}
		keyValues := [...]string{data.CcmServers[i].Host.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/sccp/sccp-ccm-list/ccm%v", predicates))
	}
	if !data.IpPrecedence.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/sccp/ip/precedence")
	}
	if !data.LocalInterface.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/sccp/local")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
