// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &DialPeerVoiceResource{}
	_ resource.ResourceWithImportState = &DialPeerVoiceResource{}
)

func NewDialPeerVoiceResource() resource.Resource {
	return &DialPeerVoiceResource{}
}

type DialPeerVoiceResource struct {
	data *IosxeProviderData
}

func (r *DialPeerVoiceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dial_peer_voice"
}

func (r *DialPeerVoiceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the Dial Peer Voice configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"delete_mode": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.").AddStringEnumDescription("all", "attributes").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("all", "attributes"),
				},
			},
			"tag": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Voice dial-peer tag").AddIntegerRangeDescription(1, 1073741823).String,
				Required:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 1073741823),
				},
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Dial peer type").AddStringEnumDescription("pots", "voip").String,
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("pots", "voip"),
				},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Dial peer specific description").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 64),
					stringvalidator.RegexMatches(regexp.MustCompile(`.*`), ""),
				},
			},
			"destination_pattern": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A full E.164 telephone number prefix").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`(((\[)[(\^)0-9,A-F#*.?+%()-]*(\])|[(\^)0-9,A-F#*.?+%()-]*)*T?($)?)`), ""),
				},
			},
			"preference": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure the preference order of this dial-peer").AddIntegerRangeDescription(0, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 10),
				},
			},
			"huntstop": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Stop hunting on Dial-Peers").String,
				Optional:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Change the Admin State of this peer to down").String,
				Optional:            true,
			},
			"vad": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use vad as necessary option").String,
				Optional:            true,
			},
			"srtp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Allow Secure calls").String,
				Optional:            true,
			},
			"session_protocol": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The session protocol to be used in getting to this peer").AddStringEnumDescription("cisco", "multicast", "sipv2").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("cisco", "multicast", "sipv2"),
				},
			},
			"session_server_group": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure voice class server-group").String,
				Optional:            true,
			},
			"session_target": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("WORD A string specifying the session target").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`(loopback:rtp)|(dns:.*)|(sip-server)|(sip-uri)|(ipv4:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?)|(ipv6:\[([0-9A-Fa-f.:])+\](:[0-9]+)?)`), ""),
				},
			},
			"session_transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Transport Layer Protocol - TLS over TCP").String,
				Optional:            true,
			},
			"session_transport_tcp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Transport Layer Protocol - TCP").String,
				Optional:            true,
			},
			"session_transport_udp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Transport Layer Protocol - UDP").String,
				Optional:            true,
			},
			"voice_class_sip_options_keepalive_profile": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Consolidate Options Keepalive profile setup").String,
				Optional:            true,
			},
			"incoming_called_number": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("An incoming called number pattern").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`(((\[)[(\^)0-9,A-F#*.?+%()-]*(\])|[(\^)0-9,A-F#*.?+%()-]*)*T?($)?)`), ""),
				},
			},
			"incoming_called_e164_pattern_map": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure voice class to match destination e164-pattern-map").String,
				Optional:            true,
			},
			"incoming_uri_via": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Match incoming topmost Via header").String,
				Optional:            true,
			},
			"incoming_uri_request": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Match incoming Request-URI").String,
				Optional:            true,
			},
			"destination_dpg": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure voice class dpg").String,
				Optional:            true,
			},
			"destination_e164_pattern_map": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure voice class to match destination e164-pattern-map").String,
				Optional:            true,
			},
			"destination_uri": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure voice class to match destination URI").String,
				Optional:            true,
			},
			"translation_profile_incoming": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Translation Profile for incoming call leg").String,
				Optional:            true,
			},
			"translation_profile_outgoing": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Translation Profile for outgoing call leg").String,
				Optional:            true,
			},
			"voice_class_sip_tenant": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set SIP-Tenant parameters").String,
				Optional:            true,
			},
			"voice_class_sip_profiles": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The sip profiles tag number to be linked as global").String,
				Optional:            true,
			},
			"voice_class_sip_profiles_inbound": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The sip profiles tag number to be linked as global").String,
				Optional:            true,
			},
			"voice_class_sip_profiles_inbound_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Turn on inbound SIP profiles feature").String,
				Optional:            true,
			},
			"voice_class_sip_bind_control_source_interface": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("GigabitEthernet IEEE 802.3z").String,
				Optional:            true,
			},
			"voice_class_sip_bind_media_source_interface": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("GigabitEthernet IEEE 802.3z").String,
				Optional:            true,
			},
			"voice_class_sip_bind_control_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Loopback interface").AddIntegerRangeDescription(0, 2147483647).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"voice_class_sip_bind_media_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Loopback interface").AddIntegerRangeDescription(0, 2147483647).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"voice_class_sip_bind_control_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ten Gigabit Ethernet").String,
				Optional:            true,
			},
			"voice_class_sip_bind_media_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ten Gigabit Ethernet").String,
				Optional:            true,
			},
			"voice_class_sip_bind_control_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ethernet Channel of interfaces").AddIntegerRangeDescription(0, 4294967295).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 4294967295),
				},
			},
			"voice_class_sip_bind_media_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ethernet Channel of interfaces").AddIntegerRangeDescription(0, 4294967295).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 4294967295),
				},
			},
			"voice_class_sip_early_offer_forced": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Forcefully Send Early-Offer").String,
				Optional:            true,
			},
			"voice_class_codec": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
			},
			"voice_class_codec_offer_all": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Offer All the codec configured in this voice-class codec").String,
				Optional:            true,
			},
			"voice_class_stun_usage": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set stun usage tag").String,
				Optional:            true,
			},
			"dtmf_relay_rtp_nte": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("RTP Named Telephone Event RFC 2833").String,
				Optional:            true,
			},
			"dtmf_relay_sip_info": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Relay via SIP INFO messages").String,
				Optional:            true,
			},
			"dtmf_relay_sip_kpml": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Relay over SIP SUBSCRIBE/NOTIFY").String,
				Optional:            true,
			},
			"dtmf_relay_sip_notify": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Relay via SIP NOTIFY messages").String,
				Optional:            true,
			},
			"ip_qos_dscp_signaling": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Specify ip DSCP").String,
				Optional:            true,
			},
			"ip_qos_dscp_signaling_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Apply DSCP to signaling packets").String,
				Optional:            true,
			},
			"max_conn": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum connections, negation sets to unlimited").AddIntegerRangeDescription(1, 2147483647).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 2147483647),
				},
			},
			"max_conn_exempt_local_media": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("max-conn value will not be updated for local media calls").String,
				Optional:            true,
			},
			"answer_address": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The Call Destination Number").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`(((\[)[(\^)0-9,A-F#*.?+%()-]*(\])|[(\^)0-9,A-F#*.?+%()-]*)*T?(\\$)?)`), ""),
				},
			},
			"codec_transparent": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Uses the endpoint codec").String,
				Optional:            true,
			},
			"media_class": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set Dial-peer media class").String,
				Optional:            true,
			},
			"voice_class_media": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set media parameters for call").String,
				Optional:            true,
			},
			"corlist_incoming": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("set the incoming Class of Restriction lists").String,
				Optional:            true,
			},
			"corlist_outgoing": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("set the outgoing Class of Restriction lists").String,
				Optional:            true,
			},
			"direct_inward_dial": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use Called Number as final call destination").String,
				Optional:            true,
			},
			"forward_digits_all": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Forward all destination digits").String,
				Optional:            true,
			},
			"forward_digits_num": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Number of right-justified dial digits to be forwarded").AddIntegerRangeDescription(0, 32).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 32),
				},
			},
			"port": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Voice port associated with this peer").String,
				Optional:            true,
			},
			"prefix": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The pattern to be appended before the dial num").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 32),
				},
			},
			"trunk_groups": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("trunk groups associated with this peer").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Trunk group ID").String,
							Required:            true,
							Validators: []validator.String{
								stringvalidator.LengthBetween(1, 64),
							},
						},
						"preference": schema.Int64Attribute{
							MarkdownDescription: helpers.NewAttributeDescription("trunk group preference value").AddIntegerRangeDescription(1, 64).String,
							Optional:            true,
							Validators: []validator.Int64{
								int64validator.Between(1, 64),
							},
						},
					},
				},
			},
		},
	}
}

func (r *DialPeerVoiceResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create

func (r *DialPeerVoiceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config DialPeerVoice

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (r *DialPeerVoiceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DialPeerVoice

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		imp, diags := helpers.IsFlagImporting(ctx, req)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}

		// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		filter := helpers.GetXpathFilter(state.getXPath())
		res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", state.getPath(), err))
			return
		}

		if helpers.IsGetConfigResponseEmpty(&res) && helpers.IsListPath(state.getXPath()) {
			tflog.Debug(ctx, fmt.Sprintf("%s: Resource does not exist", state.Id.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}

		// After `terraform import` we switch to a full read.
		if imp {
			state.fromBodyXML(ctx, res.Res)
		} else {
			state.updateFromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update

func (r *DialPeerVoiceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config DialPeerVoice

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)
		body = plan.addDeletedItemsXML(ctx, state, body)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete

func (r *DialPeerVoiceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DialPeerVoice

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		deleteMode := "all"
		if state.DeleteMode.ValueString() == "all" {
			deleteMode = "all"
		} else if state.DeleteMode.ValueString() == "attributes" {
			deleteMode = "attributes"
		}

		// NETCONF - Serialize write operations
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		if deleteMode == "all" {
			body := netconf.Body{}
			body = helpers.RemoveFromXPath(body, state.getXPath())

			if err := helpers.EditConfig(ctx, device.NetconfClient, body.Res(), device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		} else {
			body := state.addDeletePathsXML(ctx, "")

			if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import

func (r *DialPeerVoiceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	idParts = helpers.RemoveEmptyStrings(idParts)

	if len(idParts) != 1 && len(idParts) != 2 {
		expectedIdentifier := "Expected import identifier with format: '<tag>'"
		expectedIdentifier += " or '<tag>,<device>'"
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("tag"), helpers.Must(strconv.ParseInt(idParts[0], 10, 64)))...)
	if len(idParts) == 2 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
	}

	// construct path for 'id' attribute
	var state DialPeerVoice
	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getPath())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
