// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &SIPUAResource{}
	_ resource.ResourceWithImportState = &SIPUAResource{}
)

func NewSIPUAResource() resource.Resource {
	return &SIPUAResource{}
}

type SIPUAResource struct {
	data *IosxeProviderData
}

func (r *SIPUAResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sip_ua"
}

func (r *SIPUAResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the SIP UA configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"transport_udp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable SIP User Agent in UDP Mode").String,
				Optional:            true,
			},
			"transport_tcp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable SIP User Agent in TCP Mode").String,
				Optional:            true,
			},
			"transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable SIP User Agent in TLS over TCP mode (Default: All TLS versions with fallback)").String,
				Optional:            true,
			},
			"sip_server": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configure a SIP Server Interface").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`(dns:.*)|(ipv4:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?)|(ipv6:\[([0-9A-Fa-f.:])+\](:[0-9]+)?)`), ""),
				},
			},
			"redirection": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable call redirection (3XX) handling").String,
				Optional:            true,
			},
			"remote_party_id": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable Remote-Party-ID support in SIP User Agent calls").String,
				Optional:            true,
			},
			"handle_replaces": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Handle INVITE with REPLACES header at SIP spi").String,
				Optional:            true,
			},
			"reason_header_override": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable Reason header to override SIP<->Q850 Mappings").String,
				Optional:            true,
			},
			"host_registrar": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use sip-ua registrar value in Diversion and Contact header for 3xx messages").String,
				Optional:            true,
			},
			"max_forwards": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Change number of max-forwards for SIP Methods").AddIntegerRangeDescription(1, 70).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 70),
				},
			},
			"disable_early_media": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Disable early-media cut through").AddStringEnumDescription("180").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("180"),
				},
			},
			"retry_invite": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("INVITE retry value").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"retry_register": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("REGISTER retry value").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"retry_rel1xx": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Reliable 1xx retry value").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"retry_response": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Response retry value").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"retry_keepalive": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("KEEPALIVE retry value").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"timers_expires": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Time to wait for the expiration of an INVITE request").AddIntegerRangeDescription(60000, 1800000).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(60000, 1800000),
				},
			},
			"timers_trying": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Time to wait for provisional response to INVITE").AddIntegerRangeDescription(100, 1000).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(100, 1000),
				},
			},
			"timers_connection_aging_tls": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("TCP/UDP aging timer value in minutes").AddIntegerRangeDescription(60, 4320).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(60, 4320),
				},
			},
			"timers_options": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Time to wait before OPTIONS retransmission").AddIntegerRangeDescription(100, 1000).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(100, 1000),
				},
			},
			"timers_keepalive_active": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Time to wait between keepalive messages in active state").AddIntegerRangeDescription(10, 600).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(10, 600),
				},
			},
			"timers_keepalive_down": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Time to wait between keepalive messages in down state").AddIntegerRangeDescription(1, 120).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 120),
				},
			},
			"connection_reuse": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use listener port for sending requests over UDP").String,
				Optional:            true,
			},
			"connection_reuse_via_port": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Send responses to port present in Via header").String,
				Optional:            true,
			},
			"crypto_signaling_default_tls_profile": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Associate a tls-profile").String,
				Optional:            true,
			},
			"crypto_signaling_remote_addrs": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Associate an IP network to a trustpoint").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"ipv4_address": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Enter the IP address").String,
							Required:            true,
							Validators: []validator.String{
								stringvalidator.RegexMatches(regexp.MustCompile(`(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?`), ""),
							},
						},
						"subnet_mask": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Enter the mask").String,
							Required:            true,
						},
						"tls_profile": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Associate a tls-profile").String,
							Required:            true,
						},
					},
				},
			},
			"authentication_username": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("name of the user authenticating").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(4, 70),
				},
			},
			"authentication_password_type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").AddStringEnumDescription("0", "6", "7").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("0", "6", "7"),
				},
			},
			"authentication_password": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				Sensitive:           true,
			},
			"authentication_password_wo": schema.StringAttribute{
				MarkdownDescription: "The write-only value of the attribute.",
				WriteOnly:           true,
				Optional:            true,
			},
			"authentication_password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "The write-only version of the attribute.",
				Optional:            true,
			},
			"authentication_realm_username": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("name of the user authenticating").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(4, 70),
				},
			},
			"authentication_realm_password": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				Sensitive:           true,
			},
			"authentication_realm_password_wo": schema.StringAttribute{
				MarkdownDescription: "The write-only value of the attribute.",
				WriteOnly:           true,
				Optional:            true,
			},
			"authentication_realm_password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "The write-only version of the attribute.",
				Optional:            true,
			},
			"authentication_realm": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Realm at which the credentials are applicable").String,
				Optional:            true,
			},
			"credentials_numbers": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"number": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("number which is getting registered").String,
							Required:            true,
							Validators: []validator.String{
								stringvalidator.LengthBetween(4, 32),
							},
						},
						"username": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("name of the user authenticating").String,
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.LengthBetween(4, 70),
							},
						},
						"password_type": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("").AddStringEnumDescription("0", "6", "7").String,
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.OneOf("0", "6", "7"),
							},
						},
						"password": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("").String,
							Optional:            true,
							Sensitive:           true,
						},
						"password_wo": schema.StringAttribute{
							MarkdownDescription: "The write-only value of the attribute.",
							WriteOnly:           true,
							Optional:            true,
						},
						"password_wo_version": schema.Int64Attribute{
							MarkdownDescription: "The write-only version of the attribute.",
							Optional:            true,
						},
						"realm": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Realm at which the credentials are applicable").String,
							Optional:            true,
						},
					},
				},
			},
			"credentials_usernames": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"username": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("name of the user authenticating").String,
							Required:            true,
							Validators: []validator.String{
								stringvalidator.LengthBetween(4, 70),
							},
						},
						"password_type": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("").AddStringEnumDescription("0", "6", "7").String,
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.OneOf("0", "6", "7"),
							},
						},
						"password": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("").String,
							Optional:            true,
							Sensitive:           true,
						},
						"password_wo": schema.StringAttribute{
							MarkdownDescription: "The write-only value of the attribute.",
							WriteOnly:           true,
							Optional:            true,
						},
						"password_wo_version": schema.Int64Attribute{
							MarkdownDescription: "The write-only version of the attribute.",
							Optional:            true,
						},
						"realm": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("Realm at which the credentials are applicable").String,
							Optional:            true,
						},
					},
				},
			},
			"credentials_dhcp_password": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				Sensitive:           true,
			},
			"credentials_dhcp_password_wo": schema.StringAttribute{
				MarkdownDescription: "The write-only value of the attribute.",
				WriteOnly:           true,
				Optional:            true,
			},
			"credentials_dhcp_password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "The write-only version of the attribute.",
				Optional:            true,
			},
			"credentials_dhcp_realm": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Realm at which the credentials are applicable").String,
				Optional:            true,
			},
			"registrar_primary": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 128),
					stringvalidator.RegexMatches(regexp.MustCompile(`(dns:.*)|(ipv4:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?)|(ipv6:\[([0-9A-Fa-f.:])+\](:[0-9]+)?)`), ""),
				},
			},
			"registrar_primary_expires": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Default registration expires time").AddIntegerRangeDescription(60, 65535).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(60, 65535),
				},
			},
			"registrar_primary_scheme": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("URL scheme - sips or sip").AddStringEnumDescription("sip", "sips").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("sip", "sips"),
				},
			},
			"registrar_primary_tcp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use TCP as Transport Layer Protocol (default: UDP)").String,
				Optional:            true,
			},
			"registrar_primary_tls": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use TLS encryption over TCP Transport Layer Protocol").String,
				Optional:            true,
			},
			"registrar_primary_refresh_ratio": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Default registration refresh ratio").AddIntegerRangeDescription(1, 100).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 100),
				},
			},
			"registrar_secondary": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 128),
					stringvalidator.RegexMatches(regexp.MustCompile(`(dns:.*)|(ipv4:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?)|(ipv6:\[([0-9A-Fa-f.:])+\](:[0-9]+)?)`), ""),
				},
			},
			"registrar_secondary_expires": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Default registration expires time").AddIntegerRangeDescription(60, 65535).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(60, 65535),
				},
			},
			"registrar_dhcp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Registrar Server address provision via DHCP").String,
				Optional:            true,
			},
			"registrars": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Registrar Index Value for configuring multiple registrars").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							MarkdownDescription: helpers.NewAttributeDescription("Specify the rule tag").AddIntegerRangeDescription(1, 6).String,
							Required:            true,
							Validators: []validator.Int64{
								int64validator.Between(1, 6),
							},
						},
						"registrar": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("").String,
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.LengthBetween(1, 128),
								stringvalidator.RegexMatches(regexp.MustCompile(`(dns:.*)|(ipv4:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?)|(ipv6:\[([0-9A-Fa-f.:])+\](:[0-9]+)?)`), ""),
							},
						},
						"expires": schema.Int64Attribute{
							MarkdownDescription: helpers.NewAttributeDescription("Default registration expires time").AddIntegerRangeDescription(60, 65535).String,
							Optional:            true,
							Validators: []validator.Int64{
								int64validator.Between(60, 65535),
							},
						},
						"scheme": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("URL scheme - sips or sip").AddStringEnumDescription("sip", "sips").String,
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.OneOf("sip", "sips"),
							},
						},
					},
				},
			},
		},
	}
}

func (r *SIPUAResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create

func (r *SIPUAResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config SIPUA

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (r *SIPUAResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SIPUA

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		imp, diags := helpers.IsFlagImporting(ctx, req)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}

		// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		filter := helpers.GetXpathFilter(state.getXPath())
		res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", state.getPath(), err))
			return
		}

		if helpers.IsGetConfigResponseEmpty(&res) && helpers.IsListPath(state.getXPath()) {
			tflog.Debug(ctx, fmt.Sprintf("%s: Resource does not exist", state.Id.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}

		// After `terraform import` we switch to a full read.
		if imp {
			state.fromBodyXML(ctx, res.Res)
		} else {
			state.updateFromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update

func (r *SIPUAResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config SIPUA

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)
		body = plan.addDeletedItemsXML(ctx, state, body)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete

func (r *SIPUAResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SIPUA

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		deleteMode := "attributes"

		// NETCONF - Serialize write operations
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		if deleteMode == "all" {
			body := netconf.Body{}
			body = helpers.RemoveFromXPath(body, state.getXPath())

			if err := helpers.EditConfig(ctx, device.NetconfClient, body.Res(), device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		} else {
			body := state.addDeletePathsXML(ctx, "")

			if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import

func (r *SIPUAResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	idParts = helpers.RemoveEmptyStrings(idParts)

	if len(idParts) != 0 && len(idParts) != 1 {
		expectedIdentifier := "Expected import identifier with format: ''"
		expectedIdentifier += " or '<device>'"
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
		)
		return
	}
	if len(idParts) == 1 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
	}

	// construct path for 'id' attribute
	var state SIPUA
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getPath())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
