// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc

func TestAccIosxeVoiceClassSIPProfiles(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "tag", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "description", "Header normalization"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "rules.0.rule", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "rules.0.request_method", "ANY"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "rules.0.request_sip_header", "Contact"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "rules.0.request_sip_header_modify_pattern", "@.*:"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_sip_profiles.test", "rules.0.request_sip_header_modify_replace", "@cube.example.com:"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeVoiceClassSIPProfilesConfig_minimum(),
			},
			{
				Config: testAccIosxeVoiceClassSIPProfilesConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_voice_class_sip_profiles.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateIdFunc:       iosxeVoiceClassSIPProfilesImportStateIdFunc("iosxe_voice_class_sip_profiles.test"),
				ImportStateVerifyIgnore: []string{"rules.0.request_sip_header_remove", "rules.0.request_sdp_header_remove"},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc

func iosxeVoiceClassSIPProfilesImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		primary := s.RootModule().Resources[resourceName].Primary
		Tag := primary.Attributes["tag"]

		return fmt.Sprintf("%s", Tag), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal

func testAccIosxeVoiceClassSIPProfilesConfig_minimum() string {
	config := `resource "iosxe_voice_class_sip_profiles" "test" {` + "\n"
	config += `	tag = 100` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll

func testAccIosxeVoiceClassSIPProfilesConfig_all() string {
	config := `resource "iosxe_voice_class_sip_profiles" "test" {` + "\n"
	config += `	tag = 100` + "\n"
	config += `	description = "Header normalization"` + "\n"
	config += `	rules = [{` + "\n"
	config += `		rule = 10` + "\n"
	config += `		request_method = "ANY"` + "\n"
	config += `		request_sip_header = "Contact"` + "\n"
	config += `		request_sip_header_modify_pattern = "@.*:"` + "\n"
	config += `		request_sip_header_modify_replace = "@cube.example.com:"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
