// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc

func TestAccIosxeVoiceServiceVoIP(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "type", "voip"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "address_hiding", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "media_bulk_stats", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "media_statistics", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "media_disable_detailed_stats", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "mode_border_element", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "allow_connections_sip_to_sip", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "redirect_ip2ip", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "rtcp_keepalive", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "dtmf_interworking", "rtp-nte"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "gcid", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "rtcp_all_pass_through", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "ip_address_trusted_authenticate", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "srtp_fallback", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "supplementary_service_sip_moved_temporarily", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "supplementary_service_sip_handle_replaces", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "supplementary_service_media_renegotiate", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "fax_protocol", "t38"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "trace", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_session_refresh", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_session_transport_tcp_tls", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_header_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_error_passthru", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_referto_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_asserted_id_pai", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_asymmetric_payload_full", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_srtp_negotiate_cisco", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_pass_thru_headers_unsupp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_pass_thru_content_unsupp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_audio_forced", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_contact_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_requri_passing", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_update_callerid", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_anat", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_g729_annexb_all", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_privacy_policy_passthru", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_service_voip.test", "sip_conn_reuse", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeVoiceServiceVoIPConfig_minimum(),
			},
			{
				Config: testAccIosxeVoiceServiceVoIPConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_voice_service_voip.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateIdFunc:       iosxeVoiceServiceVoIPImportStateIdFunc("iosxe_voice_service_voip.test"),
				ImportStateVerifyIgnore: []string{"ip_address_trusted_call_block", "supplementary_service_sip_refer", "sip_call_service_stop", "sip_early_offer_forced", "sip_midcall_signaling_passthru"},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc

func iosxeVoiceServiceVoIPImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		primary := s.RootModule().Resources[resourceName].Primary
		Type := primary.Attributes["type"]

		return fmt.Sprintf("%s", Type), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal

func testAccIosxeVoiceServiceVoIPConfig_minimum() string {
	config := `resource "iosxe_voice_service_voip" "test" {` + "\n"
	config += `	type = "voip"` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll

func testAccIosxeVoiceServiceVoIPConfig_all() string {
	config := `resource "iosxe_voice_service_voip" "test" {` + "\n"
	config += `	type = "voip"` + "\n"
	config += `	address_hiding = true` + "\n"
	config += `	media_bulk_stats = true` + "\n"
	config += `	media_statistics = true` + "\n"
	config += `	media_disable_detailed_stats = true` + "\n"
	config += `	mode_border_element = true` + "\n"
	config += `	allow_connections_sip_to_sip = true` + "\n"
	config += `	redirect_ip2ip = true` + "\n"
	config += `	rtcp_keepalive = true` + "\n"
	config += `	dtmf_interworking = "rtp-nte"` + "\n"
	config += `	gcid = true` + "\n"
	config += `	rtcp_all_pass_through = true` + "\n"
	config += `	ip_address_trusted_authenticate = true` + "\n"
	config += `	srtp_fallback = true` + "\n"
	config += `	supplementary_service_sip_moved_temporarily = true` + "\n"
	config += `	supplementary_service_sip_handle_replaces = true` + "\n"
	config += `	supplementary_service_media_renegotiate = true` + "\n"
	config += `	fax_protocol = "t38"` + "\n"
	config += `	trace = true` + "\n"
	config += `	sip_session_refresh = true` + "\n"
	config += `	sip_session_transport_tcp_tls = true` + "\n"
	config += `	sip_header_passing = true` + "\n"
	config += `	sip_error_passthru = true` + "\n"
	config += `	sip_referto_passing = true` + "\n"
	config += `	sip_asserted_id_pai = true` + "\n"
	config += `	sip_asymmetric_payload_full = true` + "\n"
	config += `	sip_srtp_negotiate_cisco = true` + "\n"
	config += `	sip_pass_thru_headers_unsupp = true` + "\n"
	config += `	sip_pass_thru_content_unsupp = true` + "\n"
	config += `	sip_audio_forced = true` + "\n"
	config += `	sip_contact_passing = true` + "\n"
	config += `	sip_requri_passing = true` + "\n"
	config += `	sip_update_callerid = true` + "\n"
	config += `	sip_anat = false` + "\n"
	config += `	sip_g729_annexb_all = true` + "\n"
	config += `	sip_privacy_policy_passthru = true` + "\n"
	config += `	sip_conn_reuse = true` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
