// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc

func TestAccIosxeVoiceClassTLSProfile(t *testing.T) {
	if os.Getenv("C8000V") == "" {
		t.Skip("skipping test, set environment variable C8000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "tag", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "description", "CUBE TLS Profile"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "trustpoint", "CUBE-CERT"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "cn_san_validate_server", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "cn_san_names.0.tag", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "cn_san_names.0.name", "cube.example.com"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "strict_cipher", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_voice_class_tls_profile.test", "sni_send", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeVoiceClassTLSProfileConfig_minimum(),
			},
			{
				Config: testAccIosxeVoiceClassTLSProfileConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_voice_class_tls_profile.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateIdFunc:       iosxeVoiceClassTLSProfileImportStateIdFunc("iosxe_voice_class_tls_profile.test"),
				ImportStateVerifyIgnore: []string{"cn_san_validate_client", "cn_san_validate_bidirectional"},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc

func iosxeVoiceClassTLSProfileImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		primary := s.RootModule().Resources[resourceName].Primary
		Tag := primary.Attributes["tag"]

		return fmt.Sprintf("%s", Tag), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal

func testAccIosxeVoiceClassTLSProfileConfig_minimum() string {
	config := `resource "iosxe_voice_class_tls_profile" "test" {` + "\n"
	config += `	tag = 100` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll

func testAccIosxeVoiceClassTLSProfileConfig_all() string {
	config := `resource "iosxe_voice_class_tls_profile" "test" {` + "\n"
	config += `	tag = 100` + "\n"
	config += `	description = "CUBE TLS Profile"` + "\n"
	config += `	trustpoint = "CUBE-CERT"` + "\n"
	config += `	cn_san_validate_server = true` + "\n"
	config += `	cn_san_names = [{` + "\n"
	config += `		tag = 1` + "\n"
	config += `		name = "cube.example.com"` + "\n"
	config += `	}]` + "\n"
	config += `	strict_cipher = true` + "\n"
	config += `	sni_send = true` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
