// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &VoiceServiceVoIPResource{}
	_ resource.ResourceWithImportState = &VoiceServiceVoIPResource{}
)

func NewVoiceServiceVoIPResource() resource.Resource {
	return &VoiceServiceVoIPResource{}
}

type VoiceServiceVoIPResource struct {
	data *IosxeProviderData
}

func (r *VoiceServiceVoIPResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voice_service_voip"
}

func (r *VoiceServiceVoIPResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the Voice Service VoIP configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("").AddStringEnumDescription("pots", "saf", "voatm", "vofr", "voip").String,
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("pots", "saf", "voatm", "vofr", "voip"),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"address_hiding": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Address hiding (SIP-SIP)").String,
				Optional:            true,
			},
			"media_bulk_stats": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Retrieve bulk statistics is enabled").String,
				Optional:            true,
			},
			"media_statistics": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Media statistics is enabled").String,
				Optional:            true,
			},
			"media_disable_detailed_stats": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Disable detailed stats collection about the calls present").String,
				Optional:            true,
			},
			"mode_border_element": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Mode setting for Border-Element").String,
				Optional:            true,
			},
			"allow_connections_sip_to_sip": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("to-type sip").String,
				Optional:            true,
			},
			"redirect_ip2ip": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Redirect IP-to-IP calls").String,
				Optional:            true,
			},
			"rtcp_keepalive": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Generate RTCP keepalive report").String,
				Optional:            true,
			},
			"redundancy_group": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Associate redundancy-group with voice HA").AddIntegerRangeDescription(1, 2).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 2),
				},
			},
			"dtmf_interworking": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Dtmf Interworking").AddStringEnumDescription("rtp-nte", "standard").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("rtp-nte", "standard"),
				},
			},
			"emergency": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("List of Emergency Numbers").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`[0-9 ]*`), ""),
				},
			},
			"gcid": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable Global Call Identification for voip").String,
				Optional:            true,
			},
			"shutdown": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Stop VoIP services gracefully without dropping active calls").String,
				Optional:            true,
			},
			"rtcp_all_pass_through": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Pass through all the rtcp in datapath").String,
				Optional:            true,
			},
			"ip_address_trusted_authenticate": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("ip address trusted (toll fraud prevention) authenticate control flag").String,
				Optional:            true,
			},
			"ip_address_trusted_call_block": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("ip address trusted (toll fraud prevention) call-block").String,
				Optional:            true,
			},
			"ip_address_trusted_list_ipv4": schema.ListNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("ip address trusted (toll fraud prevention) list entry").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"address": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("IPv4 Address").String,
							Required:            true,
							Validators: []validator.String{
								stringvalidator.RegexMatches(regexp.MustCompile(`(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?`), ""),
							},
						},
						"mask": schema.StringAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("IPv4 Address Mask").String,
							Optional:            true,
						},
					},
				},
			},
			"srtp_fallback": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Allow Secure calls fallback to non secure").String,
				Optional:            true,
			},
			"supplementary_service_sip_moved_temporarily": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("enable/disable sip moved-temporarily").String,
				Optional:            true,
			},
			"supplementary_service_sip_handle_replaces": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Handle INVITE with REPLACES header (SIP-SIP only)").String,
				Optional:            true,
			},
			"supplementary_service_sip_refer": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("enable/disable sip refer").String,
				Optional:            true,
			},
			"supplementary_service_media_renegotiate": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable/disable Media Renegotiation").String,
				Optional:            true,
			},
			"fax_protocol": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The system-wide fax protocol type").AddStringEnumDescription("cisco", "none", "pass-through", "t38").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("cisco", "none", "pass-through", "t38"),
				},
			},
			"fax_fallback": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("fax transport to use if T.38 unsupported on far end").AddStringEnumDescription("cisco", "none", "pass-through").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("cisco", "none", "pass-through"),
				},
			},
			"trace": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Voip Trace configuration").String,
				Optional:            true,
			},
			"trace_shutdown": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Shut Voip Trace debugging").String,
				Optional:            true,
			},
			"stun_flowdata_agent_id": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set Authorization Agent Id").AddIntegerRangeDescription(0, 255).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 255),
				},
			},
			"stun_flowdata_boot_count": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set boot count").AddIntegerRangeDescription(0, 65535).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 65535),
				},
			},
			"sip_call_service_stop": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Stop SIP service - Active calls not affected").String,
				Optional:            true,
			},
			"sip_registrar_server_expires_max": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Default registration max expires time").AddIntegerRangeDescription(120, 86400).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(120, 86400),
				},
			},
			"sip_registrar_server_expires_min": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Default registration min expires time").AddIntegerRangeDescription(60, 3600).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(60, 3600),
				},
			},
			"sip_session_refresh": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable SIP session timer").String,
				Optional:            true,
			},
			"sip_session_transport_tcp_tls": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Transport Layer Protocol - TLS over TCP").String,
				Optional:            true,
			},
			"sip_header_passing": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("SIP Headers need to be passed to Applications").String,
				Optional:            true,
			},
			"sip_error_passthru": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("SIP error response pass-thru functionality").String,
				Optional:            true,
			},
			"sip_referto_passing": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Refer-To needs to be passed through for transfer").String,
				Optional:            true,
			},
			"sip_asserted_id_pai": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use privacy asserted identity").String,
				Optional:            true,
			},
			"sip_asymmetric_payload_full": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Asymmetric Support for dynamic codec and dtmf payloads").String,
				Optional:            true,
			},
			"sip_srtp_negotiate_cisco": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("allow RTP answer to SRTP offer").String,
				Optional:            true,
			},
			"sip_early_offer_forced": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Forcefully Send Early-Offer").String,
				Optional:            true,
			},
			"sip_midcall_signaling_passthru": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Passthrough SIP messages from one IP leg to another IP leg").String,
				Optional:            true,
			},
			"sip_pass_thru_headers_unsupp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Pass-through all unsupported headers").String,
				Optional:            true,
			},
			"sip_pass_thru_content_unsupp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Pass-through all unsupported content").String,
				Optional:            true,
			},
			"sip_pass_thru_content_sdp": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set Pass-through sdp mode").AddStringEnumDescription("non-rtp").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("non-rtp"),
				},
			},
			"sip_audio_forced": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Allow only audio/fax, drop all other").String,
				Optional:            true,
			},
			"sip_localhost": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Specify the DNS name for the localhost").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 128),
					stringvalidator.RegexMatches(regexp.MustCompile(`(dns:.*)`), ""),
				},
			},
			"sip_bind_control_source_interface": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("GigabitEthernet IEEE 802.3z").String,
				Optional:            true,
			},
			"sip_bind_media_source_interface": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("GigabitEthernet IEEE 802.3z").String,
				Optional:            true,
			},
			"sip_bind_control_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Loopback interface").AddIntegerRangeDescription(0, 2147483647).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"sip_bind_media_source_interface_loopback": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Loopback interface").AddIntegerRangeDescription(0, 2147483647).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"sip_bind_control_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ten Gigabit Ethernet").String,
				Optional:            true,
			},
			"sip_bind_media_source_interface_ten_gigabit_ethernet": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ten Gigabit Ethernet").String,
				Optional:            true,
			},
			"sip_bind_control_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ethernet Channel of interfaces").AddIntegerRangeDescription(0, 4294967295).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 4294967295),
				},
			},
			"sip_bind_media_source_interface_port_channel": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Ethernet Channel of interfaces").AddIntegerRangeDescription(0, 4294967295).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 4294967295),
				},
			},
			"sip_contact_passing": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("302 contact needs to be passed through for CFWD").String,
				Optional:            true,
			},
			"sip_requri_passing": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Request URI needs to be passed through").String,
				Optional:            true,
			},
			"sip_update_callerid": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable sending updates for callerid").String,
				Optional:            true,
			},
			"sip_anat": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Allow alternative network address types IPv4 and IPv6").String,
				Optional:            true,
			},
			"sip_g729_annexb_all": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("g729b representing g729a and g729b to interop with CCM").String,
				Optional:            true,
			},
			"sip_privacy_policy_passthru": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Pass through privacy values received from peer leg").String,
				Optional:            true,
			},
			"sip_conn_reuse": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("reuse the sip registration tcp connection for the end-point behind a Firewall").String,
				Optional:            true,
			},
			"sip_sip_profiles": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The sip profiles tag number to be linked as global").String,
				Optional:            true,
			},
			"sip_sip_profiles_inbound": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The sip profiles tag number to be linked as global").String,
				Optional:            true,
			},
		},
	}
}

func (r *VoiceServiceVoIPResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create

func (r *VoiceServiceVoIPResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config VoiceServiceVoIP

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (r *VoiceServiceVoIPResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state VoiceServiceVoIP

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		imp, diags := helpers.IsFlagImporting(ctx, req)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}

		// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		filter := helpers.GetXpathFilter(state.getXPath())
		res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", state.getPath(), err))
			return
		}

		if helpers.IsGetConfigResponseEmpty(&res) && helpers.IsListPath(state.getXPath()) {
			tflog.Debug(ctx, fmt.Sprintf("%s: Resource does not exist", state.Id.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}

		// After `terraform import` we switch to a full read.
		if imp {
			state.fromBodyXML(ctx, res.Res)
		} else {
			state.updateFromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update

func (r *VoiceServiceVoIPResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config VoiceServiceVoIP

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)
		body = plan.addDeletedItemsXML(ctx, state, body)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete

func (r *VoiceServiceVoIPResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state VoiceServiceVoIP

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		deleteMode := "attributes"

		// NETCONF - Serialize write operations
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		if deleteMode == "all" {
			body := netconf.Body{}
			body = helpers.RemoveFromXPath(body, state.getXPath())

			if err := helpers.EditConfig(ctx, device.NetconfClient, body.Res(), device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		} else {
			body := state.addDeletePathsXML(ctx, "")

			if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import

func (r *VoiceServiceVoIPResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	idParts = helpers.RemoveEmptyStrings(idParts)

	if len(idParts) != 1 && len(idParts) != 2 {
		expectedIdentifier := "Expected import identifier with format: '<type>'"
		expectedIdentifier += " or '<type>,<device>'"
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("type"), idParts[0])...)
	if len(idParts) == 2 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
	}

	// construct path for 'id' attribute
	var state VoiceServiceVoIP
	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getPath())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
